from datetime import datetime, timedelta

# Sample adverts data array
sample_adverts = [
    {
        'id': 'ad_001',
        'type': 'advertisement',
        'brand': 'TrailBlaze Gear',
        'title': 'Discover Your Next Adventure',
        'text': 'Premium outdoor gear for every expedition. From mountain peaks to forest trails, gear up with equipment trusted by adventurers worldwide. Free shipping on orders over $75!',
        'image': 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=800&h=600&fit=crop',
        'cta_text': 'Shop Now',
        'cta_link': 'https://trailblazegear.com/adventure-collection',
        'category': 'Outdoor Gear',
        'promoted': True,
        'target_audience': ['hiking', 'adventure', 'outdoor', 'camping'],
        'created_at': datetime.now() - timedelta(hours=2),
        'budget_spent': 127.50,
        'impressions': 2847,
        'clicks': 89
    },
    {
        'id': 'ad_002',
        'type': 'advertisement',
        'brand': 'ZenFlex Yoga',
        'title': 'Transform Your Practice',
        'text': 'Join thousands who have transformed their wellness journey with ZenFlex. Premium yoga mats, blocks, and accessories designed for every level. Start your mindful movement today.',
        'image': 'https://images.unsplash.com/photo-1506629905607-67d7f73de7ce?w=800&h=600&fit=crop',
        'cta_text': 'Start Free Trial',
        'cta_link': 'https://zenflexonline.com/free-trial',
        'category': 'Health & Wellness',
        'promoted': True,
        'target_audience': ['yoga', 'wellness', 'fitness', 'mindfulness', 'meditation'],
        'created_at': datetime.now() - timedelta(hours=6),
        'budget_spent': 203.75,
        'impressions': 4521,
        'clicks': 156
    },
    {
        'id': 'ad_003',
        'type': 'advertisement',
        'brand': 'FreshBite Meals',
        'title': 'Healthy Meals Made Simple',
        'text': 'Skip the grocery store stress. Get chef-prepared, nutritious meals delivered weekly. Fresh ingredients, bold flavors, zero prep time. Use code FRESH20 for 20% off your first order!',
        'image': 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&h=600&fit=crop',
        'cta_text': 'Order Now',
        'cta_link': 'https://freshbitemeals.com/weekly-plans',
        'category': 'Food & Beverage',
        'promoted': True,
        'target_audience': ['healthy_eating', 'meal_prep', 'convenience', 'busy_professionals'],
        'created_at': datetime.now() - timedelta(hours=4),
        'budget_spent': 89.30,
        'impressions': 1923,
        'clicks': 67
    },
    {
        'id': 'ad_004',
        'type': 'advertisement',
        'brand': 'CodeCraft Academy',
        'title': 'Learn to Code in 12 Weeks',
        'text': 'Transform your career with our intensive coding bootcamp. Master JavaScript, Python, and React with hands-on projects. 90% job placement rate. Scholarships available!',
        'image': 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=800&h=600&fit=crop',
        'cta_text': 'Apply Today',
        'cta_link': 'https://codecraftacademy.com/bootcamp',
        'category': 'Education',
        'promoted': True,
        'target_audience': ['programming', 'career_change', 'education', 'technology'],
        'created_at': datetime.now() - timedelta(hours=8),
        'budget_spent': 156.75,
        'impressions': 3241,
        'clicks': 112
    },
    {
        'id': 'ad_005',
        'type': 'advertisement',
        'brand': 'EcoClean Solutions',
        'title': 'Clean Green, Live Better',
        'text': 'Switch to our eco-friendly cleaning products made from plant-based ingredients. Safe for your family, pets, and the planet. Subscribe and save 15% on every delivery.',
        'image': 'https://images.unsplash.com/photo-1563453392212-326f5e854473?w=800&h=600&fit=crop',
        'cta_text': 'Shop Eco',
        'cta_link': 'https://ecoclean.com/starter-kit',
        'category': 'Home & Garden',
        'promoted': True,
        'target_audience': ['eco_friendly', 'sustainability', 'family', 'home_care'],
        'created_at': datetime.now() - timedelta(hours=12),
        'budget_spent': 92.40,
        'impressions': 2156,
        'clicks': 78
    },
    {
        'id': 'ad_006',
        'type': 'advertisement',
        'brand': 'FitTrack Pro',
        'title': 'Your Personal Fitness Coach',
        'text': 'AI-powered fitness tracking with personalized workout plans. Track progress, set goals, and stay motivated with our smart wearable. 30-day free trial included.',
        'image': 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&h=600&fit=crop',
        'cta_text': 'Start Trial',
        'cta_link': 'https://fittrackpro.com/get-started',
        'category': 'Health & Fitness',
        'promoted': True,
        'target_audience': ['fitness', 'health', 'technology', 'workout', 'wellness'],
        'created_at': datetime.now() - timedelta(hours=1),
        'budget_spent': 213.60,
        'impressions': 4892,
        'clicks': 198
    },
    {
        'id': 'ad_007',
        'type': 'advertisement',
        'brand': 'Artisan Coffee Co.',
        'title': 'Coffee That Tells a Story',
        'text': 'Single-origin beans sourced directly from farmers worldwide. Roasted to perfection in small batches. Experience the difference ethical sourcing makes. Free shipping over $35.',
        'image': 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&h=600&fit=crop',
        'cta_text': 'Browse Beans',
        'cta_link': 'https://artisancoffee.co/collections',
        'category': 'Food & Beverage',
        'promoted': True,
        'target_audience': ['coffee', 'artisan', 'ethical', 'gourmet', 'fair_trade'],
        'created_at': datetime.now() - timedelta(hours=18),
        'budget_spent': 134.85,
        'impressions': 2764,
        'clicks': 93
    },
    {
        'id': 'ad_008',
        'type': 'advertisement',
        'brand': 'MindSpace Meditation',
        'title': 'Find Your Inner Peace',
        'text': 'Guided meditation sessions for stress relief, better sleep, and mindful living. Join millions finding calm in just 10 minutes a day. First month free for new users.',
        'image': 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&h=600&fit=crop',
        'cta_text': 'Try Free',
        'cta_link': 'https://mindspace.app/free-trial',
        'category': 'Health & Wellness',
        'promoted': True,
        'target_audience': ['meditation', 'mindfulness', 'stress_relief', 'mental_health', 'wellness'],
        'created_at': datetime.now() - timedelta(hours=3),
        'budget_spent': 167.20,
        'impressions': 3658,
        'clicks': 145
    },
    {
        'id': 'ad_009',
        'type': 'advertisement',
        'brand': 'TechSafe Security',
        'title': 'Protect Your Digital Life',
        'text': 'Advanced cybersecurity solutions for home and business. Real-time threat detection, secure VPN, and identity protection. Keep your data safe from cyber criminals.',
        'image': 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800&h=600&fit=crop',
        'cta_text': 'Get Protected',
        'cta_link': 'https://techsafe.com/protection-plans',
        'category': 'Technology',
        'promoted': True,
        'target_audience': ['cybersecurity', 'privacy', 'business', 'technology', 'data_protection'],
        'created_at': datetime.now() - timedelta(hours=7),
        'budget_spent': 245.90,
        'impressions': 5123,
        'clicks': 167
    },
    {
        'id': 'ad_010',
        'type': 'advertisement',
        'brand': 'GreenThumb Gardens',
        'title': 'Grow Your Dream Garden',
        'text': 'Everything you need for a thriving garden. From seeds to tools, organic fertilizers to raised beds. Expert advice included with every purchase. Spring sale now on!',
        'image': 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&h=600&fit=crop',
        'cta_text': 'Shop Garden',
        'cta_link': 'https://greenthumb.com/spring-collection',
        'category': 'Home & Garden',
        'promoted': True,
        'target_audience': ['gardening', 'plants', 'organic', 'home_improvement', 'sustainability'],
        'created_at': datetime.now() - timedelta(hours=14),
        'budget_spent': 78.45,
        'impressions': 1647,
        'clicks': 52
    },
    {
        'id': 'ad_011',
        'type': 'advertisement',
        'brand': 'StyleBox Fashion',
        'title': 'Fashion That Fits Your Life',
        'text': 'Curated clothing subscription tailored to your style preferences. Professional stylists pick pieces you\'ll love. Skip, swap, or keep forever. Style quiz takes 2 minutes.',
        'image': 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&h=600&fit=crop',
        'cta_text': 'Take Quiz',
        'cta_link': 'https://stylebox.com/style-quiz',
        'category': 'Fashion & Beauty',
        'promoted': True,
        'target_audience': ['fashion', 'style', 'subscription', 'personal_styling', 'clothing'],
        'created_at': datetime.now() - timedelta(hours=9),
        'budget_spent': 189.75,
        'impressions': 4267,
        'clicks': 176
    },
    {
        'id': 'ad_012',
        'type': 'advertisement',
        'brand': 'PetPal Services',
        'title': 'Your Pet\'s Best Friend',
        'text': 'Professional pet care when you can\'t be there. Dog walking, pet sitting, and grooming services. Trusted, insured caregivers who love animals as much as you do.',
        'image': 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=800&h=600&fit=crop',
        'cta_text': 'Book Now',
        'cta_link': 'https://petpalservices.com/book-care',
        'category': 'Pet Care',
        'promoted': True,
        'target_audience': ['pets', 'dog_walking', 'pet_sitting', 'pet_care', 'animal_lovers'],
        'created_at': datetime.now() - timedelta(hours=5),
        'budget_spent': 112.30,
        'impressions': 2439,
        'clicks': 84
    },
    {
        'id': 'ad_013',
        'type': 'advertisement',
        'brand': 'SmartHome Hub',
        'title': 'Control Your Home with a Tap',
        'text': 'Transform any home into a smart home. Voice control, automated lighting, security monitoring, and energy savings. Easy setup, no wiring required. Compatible with all devices.',
        'image': 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=800&h=600&fit=crop',
        'cta_text': 'Get Smart',
        'cta_link': 'https://smarthomehub.com/starter-kit',
        'category': 'Technology',
        'promoted': True,
        'target_audience': ['smart_home', 'automation', 'technology', 'convenience', 'energy_saving'],
        'created_at': datetime.now() - timedelta(hours=11),
        'budget_spent': 198.60,
        'impressions': 4156,
        'clicks': 134
    },
    {
        'id': 'ad_014',
        'type': 'advertisement',
        'brand': 'CloudStream Pro',
        'title': 'Stream Everything, Everywhere',
        'text': 'Unlimited streaming across all your devices. 10,000+ movies, shows, documentaries, and live sports. No ads, no limits, no contracts. First 2 weeks absolutely free.',
        'image': 'https://images.unsplash.com/photo-1522869635100-9f4c5e86aa37?w=800&h=600&fit=crop',
        'cta_text': 'Stream Free',
        'cta_link': 'https://cloudstreampro.com/free-trial',
        'category': 'Entertainment',
        'promoted': True,
        'target_audience': ['streaming', 'entertainment', 'movies', 'tv_shows', 'sports'],
        'created_at': datetime.now() - timedelta(hours=16),
        'budget_spent': 267.40,
        'impressions': 5847,
        'clicks': 223
    },
    {
        'id': 'ad_015',
        'type': 'advertisement',
        'brand': 'SolarMax Energy',
        'title': 'Power Your Home with Sunshine',
        'text': 'Cut your electricity bill by 90% with solar panels. Professional installation, 25-year warranty, and government rebates available. Free home assessment and quote.',
        'image': 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=800&h=600&fit=crop',
        'cta_text': 'Get Quote',
        'cta_link': 'https://solarmaxenergy.com/free-assessment',
        'category': 'Home & Garden',
        'promoted': True,
        'target_audience': ['solar_energy', 'sustainability', 'home_improvement', 'energy_savings', 'eco_friendly'],
        'created_at': datetime.now() - timedelta(hours=20),
        'budget_spent': 312.85,
        'impressions': 6234,
        'clicks': 189
    },
    {
        'id': 'ad_016',
        'type': 'advertisement',
        'brand': 'CraftBrew Academy',
        'title': 'Brew Beer Like a Master',
        'text': 'Learn the art of homebrewing with expert-led online courses. From beginner to advanced techniques. Includes brewing kit and ingredients. Join 5,000+ brewing enthusiasts.',
        'image': 'https://images.unsplash.com/photo-1608270586620-248524c67de9?w=800&h=600&fit=crop',
        'cta_text': 'Start Brewing',
        'cta_link': 'https://craftbrewacademy.com/courses',
        'category': 'Food & Beverage',
        'promoted': True,
        'target_audience': ['homebrewing', 'craft_beer', 'hobbies', 'diy', 'beer_enthusiasts'],
        'created_at': datetime.now() - timedelta(hours=6),
        'budget_spent': 143.70,
        'impressions': 2876,
        'clicks': 97
    },
    {
        'id': 'ad_017',
        'type': 'advertisement',
        'brand': 'MoneyWise Financial',
        'title': 'Take Control of Your Finances',
        'text': 'Personal financial planning made simple. Investment advice, retirement planning, and debt management. Certified advisors help you build wealth. Free consultation available.',
        'image': 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=600&fit=crop',
        'cta_text': 'Get Advice',
        'cta_link': 'https://moneywise.com/consultation',
        'category': 'Financial Services',
        'promoted': True,
        'target_audience': ['finance', 'investment', 'retirement', 'financial_planning', 'wealth_building'],
        'created_at': datetime.now() - timedelta(hours=13),
        'budget_spent': 187.25,
        'impressions': 3542,
        'clicks': 128
    },
    {
        'id': 'ad_018',
        'type': 'advertisement',
        'brand': 'AdventureGear Pro',
        'title': 'Gear Up for Epic Adventures',
        'text': 'Premium camping and hiking equipment built for extreme conditions. Lightweight tents, sleeping bags, and backpacks. Used by professional explorers worldwide. Lifetime warranty.',
        'image': 'https://images.unsplash.com/photo-1504851149312-7a075b496cc7?w=800&h=600&fit=crop',
        'cta_text': 'Explore Gear',
        'cta_link': 'https://adventuregear.pro/collections',
        'category': 'Outdoor Gear',
        'promoted': True,
        'target_audience': ['camping', 'hiking', 'backpacking', 'outdoor_adventure', 'extreme_sports'],
        'created_at': datetime.now() - timedelta(hours=2),
        'budget_spent': 156.90,
        'impressions': 3287,
        'clicks': 115
    },
    {
        'id': 'ad_019',
        'type': 'advertisement',
        'brand': 'LanguageMaster',
        'title': 'Speak Fluently in 90 Days',
        'text': 'AI-powered language learning with native speaker practice. Master Spanish, French, Italian, or German. Personalized lessons adapt to your learning style. Money-back guarantee.',
        'image': 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=600&fit=crop',
        'cta_text': 'Start Learning',
        'cta_link': 'https://languagemaster.com/free-lesson',
        'category': 'Education',
        'promoted': True,
        'target_audience': ['language_learning', 'education', 'travel', 'career_development', 'personal_growth'],
        'created_at': datetime.now() - timedelta(hours=15),
        'budget_spent': 234.50,
        'impressions': 4923,
        'clicks': 178
    },
    {
        'id': 'ad_020',
        'type': 'advertisement',
        'brand': 'SkinGlow Beauty',
        'title': 'Radiant Skin Starts Here',
        'text': 'Clinically proven skincare routine with natural ingredients. Reduce wrinkles, brighten complexion, and restore youthful glow. Dermatologist recommended. 60-day results guarantee.',
        'image': 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=800&h=600&fit=crop',
        'cta_text': 'Try Now',
        'cta_link': 'https://skinglowbeauty.com/skincare-kit',
        'category': 'Fashion & Beauty',
        'promoted': True,
        'target_audience': ['skincare', 'beauty', 'anti_aging', 'natural_products', 'self_care'],
        'created_at': datetime.now() - timedelta(hours=8),
        'budget_spent': 176.80,
        'impressions': 3891,
        'clicks': 152
    },
    {
        'id': 'ad_021',
        'type': 'advertisement',
        'brand': 'TravelEasy Booking',
        'title': 'Your Next Adventure Awaits',
        'text': 'Book flights, hotels, and rental cars at unbeatable prices. Exclusive deals and rewards for members. 24/7 customer support and flexible cancellation. Start exploring today!',
        'image': 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=800&h=600&fit=crop',
        'cta_text': 'Book Travel',
        'cta_link': 'https://traveleasy.com/search',
        'category': 'Travel',
        'promoted': True,
        'target_audience': ['travel', 'vacation', 'flights', 'hotels', 'adventure'],
        'created_at': datetime.now() - timedelta(hours=10),
        'budget_spent': 298.15,
        'impressions': 6187,
        'clicks': 241
    },
    {
        'id': 'ad_022',
        'type': 'advertisement',
        'brand': 'WorkSpace Solutions',
        'title': 'Design Your Perfect Office',
        'text': 'Ergonomic furniture and productivity tools for home offices. Standing desks, supportive chairs, and organization systems. Increase productivity and comfort. Free design consultation.',
        'image': 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=600&fit=crop',
        'cta_text': 'Shop Office',
        'cta_link': 'https://workspacesolutions.com/home-office',
        'category': 'Home & Garden',
        'promoted': True,
        'target_audience': ['home_office', 'productivity', 'ergonomics', 'furniture', 'work_from_home'],
        'created_at': datetime.now() - timedelta(hours=4),
        'budget_spent': 164.30,
        'impressions': 3456,
        'clicks': 119
    },
    {
        'id': 'ad_023',
        'type': 'advertisement',
        'brand': 'FlexFit Studio',
        'title': 'Transform Your Body at Home',
        'text': 'Live and on-demand fitness classes from certified trainers. Yoga, HIIT, strength training, and dance. No equipment needed. Join thousands getting fit from home. First class free!',
        'image': 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&h=600&fit=crop',
        'cta_text': 'Join Free',
        'cta_link': 'https://flexfitstudio.com/free-class',
        'category': 'Health & Fitness',
        'promoted': True,
        'target_audience': ['fitness', 'home_workout', 'yoga', 'strength_training', 'wellness'],
        'created_at': datetime.now() - timedelta(hours=3),
        'budget_spent': 145.60,
        'impressions': 3124,
        'clicks': 108
    },
    {
        'id': 'ad_024',
        'type': 'advertisement',
        'brand': 'BookNook Library',
        'title': 'Unlimited Books, One Price',
        'text': 'Access 500,000+ ebooks and audiobooks instantly. New releases, bestsellers, and classics. Read on any device, offline capability. Perfect for book lovers. 7-day free trial.',
        'image': 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800&h=600&fit=crop',
        'cta_text': 'Read Free',
        'cta_link': 'https://booknook.com/trial',
        'category': 'Entertainment',
        'promoted': True,
        'target_audience': ['reading', 'books', 'audiobooks', 'literature', 'education'],
        'created_at': datetime.now() - timedelta(hours=17),
        'budget_spent': 123.40,
        'impressions': 2765,
        'clicks': 89
    },
    {
        'id': 'ad_025',
        'type': 'advertisement',
        'brand': 'CryptoSafe Wallet',
        'title': 'Secure Your Digital Assets',
        'text': 'Military-grade cryptocurrency wallet with multi-layer security. Store Bitcoin, Ethereum, and 1000+ coins safely. Hardware and software protection. Trusted by 2M+ users worldwide.',
        'image': 'https://images.unsplash.com/photo-1518546305927-5a555bb7020d?w=800&h=600&fit=crop',
        'cta_text': 'Get Wallet',
        'cta_link': 'https://cryptosafe.com/wallet',
        'category': 'Financial Services',
        'promoted': True,
        'target_audience': ['cryptocurrency', 'bitcoin', 'digital_assets', 'blockchain', 'investment'],
        'created_at': datetime.now() - timedelta(hours=21),
        'budget_spent': 289.75,
        'impressions': 5234,
        'clicks': 167
    },
    {
        'id': 'ad_026',
        'type': 'advertisement',
        'brand': 'AutoCare Express',
        'title': 'Keep Your Car Running Smooth',
        'text': 'Professional mobile car maintenance at your location. Oil changes, brake service, and diagnostics. Certified mechanics, quality parts, fair prices. Book online in 60 seconds.',
        'image': 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=800&h=600&fit=crop',
        'cta_text': 'Book Service',
        'cta_link': 'https://autocareexpress.com/booking',
        'category': 'Automotive',
        'promoted': True,
        'target_audience': ['car_maintenance', 'automotive', 'mobile_service', 'convenience', 'auto_repair'],
        'created_at': datetime.now() - timedelta(hours=7),
        'budget_spent': 178.90,
        'impressions': 3967,
        'clicks': 142
    },
    {
        'id': 'ad_027',
        'type': 'advertisement',
        'brand': 'KitchenMaster Tools',
        'title': 'Cook Like a Professional Chef',
        'text': 'Premium kitchen knives and cooking tools used by top restaurants. German steel, lifetime sharpening, ergonomic design. Elevate your culinary skills. 30-day money-back guarantee.',
        'image': 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&h=600&fit=crop',
        'cta_text': 'Shop Knives',
        'cta_link': 'https://kitchenmaster.com/chef-collection',
        'category': 'Home & Garden',
        'promoted': True,
        'target_audience': ['cooking', 'kitchen_tools', 'culinary', 'food_preparation', 'chef_quality'],
        'created_at': datetime.now() - timedelta(hours=12),
        'budget_spent': 156.25,
        'impressions': 3456,
        'clicks': 123
    },
    {
        'id': 'ad_028',
        'type': 'advertisement',
        'brand': 'PhotographyPro Academy',
        'title': 'Master Photography in 30 Days',
        'text': 'Learn from award-winning photographers. Portrait, landscape, and street photography courses. Live workshops, feedback sessions, and community support. Certificate included.',
        'image': 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800&h=600&fit=crop',
        'cta_text': 'Learn Photography',
        'cta_link': 'https://photographypro.com/courses',
        'category': 'Education',
        'promoted': True,
        'target_audience': ['photography', 'creative_skills', 'art', 'education', 'visual_arts'],
        'created_at': datetime.now() - timedelta(hours=19),
        'budget_spent': 167.80,
        'impressions': 3721,
        'clicks': 134
    },
    {
        'id': 'ad_029',
        'type': 'advertisement',
        'brand': 'SleepWell Mattress',
        'title': 'Your Best Sleep Starts Tonight',
        'text': 'Memory foam mattress engineered for perfect support and cooling comfort. 365-night trial, free shipping both ways. Say goodbye to restless nights forever.',
        'image': 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=800&h=600&fit=crop',
        'cta_text': 'Try Risk-Free',
        'cta_link': 'https://sleepwellmattress.com/trial',
        'category': 'Home & Garden',
        'promoted': True,
        'target_audience': ['sleep', 'comfort', 'mattress', 'home_improvement', 'wellness'],
        'created_at': datetime.now() - timedelta(hours=5),
        'budget_spent': 234.15,
        'impressions': 4892,
        'clicks': 187
    },
    {
        'id': 'ad_030',
        'type': 'advertisement',
        'brand': 'GameZone Unlimited',
        'title': 'Play 1000+ Games Instantly',
        'text': 'Cloud gaming service with no downloads required. Latest AAA titles, indie gems, and retro classics. Play on any device with internet. First month only $1!',
        'image': 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800&h=600&fit=crop',
        'cta_text': 'Play Now',
        'cta_link': 'https://gamezone.com/unlimited',
        'category': 'Entertainment',
        'promoted': True,
        'target_audience': ['gaming', 'entertainment', 'cloud_gaming', 'video_games', 'technology'],
        'created_at': datetime.now() - timedelta(hours=9),
        'budget_spent': 198.50,
        'impressions': 4356,
        'clicks': 176
    },
    {
        'id': 'ad_031',
        'type': 'advertisement',
        'brand': 'NutriBoost Supplements',
        'title': 'Supercharge Your Health',
        'text': 'Premium vitamins and supplements made from organic ingredients. Boost energy, immune system, and mental clarity. Third-party tested for purity. Subscribe and save 25%.',
        'image': 'https://images.unsplash.com/photo-1559181567-c3190ca9959b?w=800&h=600&fit=crop',
        'cta_text': 'Shop Vitamins',
        'cta_link': 'https://nutriboost.com/supplements',
        'category': 'Health & Wellness',
        'promoted': True,
        'target_audience': ['supplements', 'health', 'nutrition', 'wellness', 'vitamins'],
        'created_at': datetime.now() - timedelta(hours=14),
        'budget_spent': 187.65,
        'impressions': 4123,
        'clicks': 158
    },
    {
        'id': 'ad_032',
        'type': 'advertisement',
        'brand': 'CleanSpace Air',
        'title': 'Breathe Pure Air at Home',
        'text': 'Advanced air purification system removes 99.97% of pollutants, allergens, and odors. HEPA filtration, smart sensors, whisper-quiet operation. Perfect for allergies and asthma.',
        'image': 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop',
        'cta_text': 'Purify Air',
        'cta_link': 'https://cleanspaceair.com/purifiers',
        'category': 'Home & Garden',
        'promoted': True,
        'target_audience': ['air_quality', 'health', 'allergies', 'home_improvement', 'wellness'],
        'created_at': datetime.now() - timedelta(hours=1),
        'budget_spent': 145.30,
        'impressions': 3287,
        'clicks': 112
    },
    {
        'id': 'ad_033',
        'type': 'advertisement',
        'brand': 'RocketLearn Skills',
        'title': 'Master Digital Marketing Today',
        'text': 'Comprehensive online courses in SEO, social media, and Google Ads. Learn from industry experts with real case studies. Get certified and boost your career. Job guarantee included.',
        'image': 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=600&fit=crop',
        'cta_text': 'Start Course',
        'cta_link': 'https://rocketlearn.com/digital-marketing',
        'category': 'Education',
        'promoted': True,
        'target_audience': ['digital_marketing', 'career_development', 'online_learning', 'certification', 'business_skills'],
        'created_at': datetime.now() - timedelta(hours=6),
        'budget_spent': 201.40,
        'impressions': 4567,
        'clicks': 165
    },
    {
        'id': 'ad_034',
        'type': 'advertisement',
        'brand': 'PurePaws Pet Food',
        'title': 'Nutrition Your Pet Deserves',
        'text': 'Grain-free, organic pet food made with real meat and vegetables. Vet-approved recipes for dogs and cats of all ages. Free feeding guide and satisfaction guarantee.',
        'image': 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=800&h=600&fit=crop',
        'cta_text': 'Shop Food',
        'cta_link': 'https://purepaws.com/premium-nutrition',
        'category': 'Pet Care',
        'promoted': True,
        'target_audience': ['pet_food', 'organic', 'pet_health', 'nutrition', 'animal_care'],
        'created_at': datetime.now() - timedelta(hours=18),
        'budget_spent': 134.85,
        'impressions': 2943,
        'clicks': 98
    },
    {
        'id': 'ad_035',
        'type': 'advertisement',
        'brand': 'WealthBuilder Investment',
        'title': 'Build Wealth While You Sleep',
        'text': 'Automated investment platform that grows your money 24/7. Diversified portfolios, low fees, tax optimization. Start with just $100. See how your money can work for you.',
        'image': 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=800&h=600&fit=crop',
        'cta_text': 'Start Investing',
        'cta_link': 'https://wealthbuilder.com/get-started',
        'category': 'Financial Services',
        'promoted': True,
        'target_audience': ['investing', 'wealth_building', 'finance', 'passive_income', 'retirement'],
        'created_at': datetime.now() - timedelta(hours=11),
        'budget_spent': 267.90,
        'impressions': 5432,
        'clicks': 198
    },
    {
        'id': 'ad_036',
        'type': 'advertisement',
        'brand': 'ArtisanBake Supplies',
        'title': 'Bake Like a Professional',
        'text': 'Premium baking tools and ingredients used by top pastry chefs. Silicone molds, precision scales, European chocolates. Everything you need for perfect results every time.',
        'image': 'https://images.unsplash.com/photo-1486427944299-d1955d23e34d?w=800&h=600&fit=crop',
        'cta_text': 'Shop Baking',
        'cta_link': 'https://artisanbake.com/professional-tools',
        'category': 'Food & Beverage',
        'promoted': True,
        'target_audience': ['baking', 'pastry', 'cooking', 'kitchen_tools', 'culinary'],
        'created_at': datetime.now() - timedelta(hours=4),
        'budget_spent': 156.70,
        'impressions': 3278,
        'clicks': 117
    },
    {
        'id': 'ad_037',
        'type': 'advertisement',
        'brand': 'SecureVPN Pro',
        'title': 'Browse Safely and Privately',
        'text': 'Military-grade VPN protection for all your devices. Access blocked content, protect personal data, no-logs policy. 30-day money-back guarantee. Connect up to 10 devices.',
        'image': 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800&h=600&fit=crop',
        'cta_text': 'Get Protected',
        'cta_link': 'https://securevpn.pro/premium',
        'category': 'Technology',
        'promoted': True,
        'target_audience': ['vpn', 'privacy', 'security', 'online_protection', 'streaming'],
        'created_at': datetime.now() - timedelta(hours=15),
        'budget_spent': 189.25,
        'impressions': 4156,
        'clicks': 148
    },
    {
        'id': 'ad_038',
        'type': 'advertisement',
        'brand': 'RelaxSpa At Home',
        'title': 'Transform Your Bathroom into a Spa',
        'text': 'Luxury bath products with essential oils and natural ingredients. Bath bombs, salts, and aromatherapy candles. Create your personal wellness retreat. Gift sets available.',
        'image': 'https://images.unsplash.com/photo-1571173655423-fd3ef7d7ec6b?w=800&h=600&fit=crop',
        'cta_text': 'Shop Spa',
        'cta_link': 'https://relaxspa.com/bath-collection',
        'category': 'Health & Wellness',
        'promoted': True,
        'target_audience': ['spa', 'relaxation', 'self_care', 'aromatherapy', 'wellness'],
        'created_at': datetime.now() - timedelta(hours=8),
        'budget_spent': 143.60,
        'impressions': 3089,
        'clicks': 112
    },
    {
        'id': 'ad_039',
        'type': 'advertisement',
        'brand': 'ElectricRide Bikes',
        'title': 'Ride Further, Arrive Faster',
        'text': 'Premium electric bikes for commuting and adventure. 50-mile range, fast charging, built-in GPS. Eco-friendly transportation that saves money and time. Test ride available.',
        'image': 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=800&h=600&fit=crop',
        'cta_text': 'Test Ride',
        'cta_link': 'https://electricride.com/test-drive',
        'category': 'Transportation',
        'promoted': True,
        'target_audience': ['electric_bikes', 'eco_friendly', 'commuting', 'cycling', 'sustainable_transport'],
        'created_at': datetime.now() - timedelta(hours=12),
        'budget_spent': 234.80,
        'impressions': 4891,
        'clicks': 176
    },
    {
        'id': 'ad_040',
        'type': 'advertisement',
        'brand': 'MasterChef Academy',
        'title': 'Cook Like a Michelin Star Chef',
        'text': 'Online culinary school with world-class chefs as instructors. Learn knife skills, sauces, plating, and more. Interactive lessons, recipe library, and community support.',
        'image': 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=600&fit=crop',
        'cta_text': 'Start Cooking',
        'cta_link': 'https://masterchefacademy.com/courses',
        'category': 'Education',
        'promoted': True,
        'target_audience': ['cooking', 'culinary_arts', 'chef_training', 'food', 'skills_development'],
        'created_at': datetime.now() - timedelta(hours=20),
        'budget_spent': 178.45,
        'impressions': 3756,
        'clicks': 138
    },
    {
        'id': 'ad_041',
        'type': 'advertisement',
        'brand': 'StyleFusion Furniture',
        'title': 'Furniture That Defines You',
        'text': 'Modern furniture that combines style, comfort, and sustainability. Handcrafted pieces using eco-friendly materials. Free design consultation and white-glove delivery.',
        'image': 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&h=600&fit=crop',
        'cta_text': 'Browse Furniture',
        'cta_link': 'https://stylefusion.com/collections',
        'category': 'Home & Garden',
        'promoted': True,
        'target_audience': ['furniture', 'interior_design', 'home_decor', 'sustainable', 'modern_living'],
        'created_at': datetime.now() - timedelta(hours=2),
        'budget_spent': 156.30,
        'impressions': 3421,
        'clicks': 124
    },
    {
        'id': 'ad_042',
        'type': 'advertisement',
        'brand': 'PowerUp Protein',
        'title': 'Fuel Your Fitness Goals',
        'text': 'Clean protein powder with 25g per serving. No artificial ingredients, multiple flavors, easy mixing. Trusted by athletes and fitness enthusiasts. Subscribe and save 20%.',
        'image': 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=800&h=600&fit=crop',
        'cta_text': 'Shop Protein',
        'cta_link': 'https://powerupprotein.com/shop',
        'category': 'Health & Fitness',
        'promoted': True,
        'target_audience': ['protein', 'fitness', 'nutrition', 'supplements', 'muscle_building'],
        'created_at': datetime.now() - timedelta(hours=16),
        'budget_spent': 167.85,
        'impressions': 3689,
        'clicks': 143
    },
    {
        'id': 'ad_043',
        'type': 'advertisement',
        'brand': 'CloudBackup Secure',
        'title': 'Never Lose Your Data Again',
        'text': 'Automatic cloud backup for all your files, photos, and documents. Military-grade encryption, unlimited storage, cross-platform sync. Peace of mind for just $5/month.',
        'image': 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&h=600&fit=crop',
        'cta_text': 'Backup Now',
        'cta_link': 'https://cloudbackup.com/secure-storage',
        'category': 'Technology',
        'promoted': True,
        'target_audience': ['data_backup', 'cloud_storage', 'security', 'file_protection', 'business'],
        'created_at': datetime.now() - timedelta(hours=13),
        'budget_spent': 145.90,
        'impressions': 3234,
        'clicks': 118
    },
    {
        'id': 'ad_044',
        'type': 'advertisement',
        'brand': 'GreenClean Laundry',
        'title': 'Clean Clothes, Clean Planet',
        'text': 'Eco-friendly laundry detergent pods made from plant-based ingredients. Powerful cleaning without harsh chemicals. Safe for sensitive skin and septic systems. Bulk savings available.',
        'image': 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=800&h=600&fit=crop',
        'cta_text': 'Shop Clean',
        'cta_link': 'https://greenclean.com/laundry-pods',
        'category': 'Home & Garden',
        'promoted': True,
        'target_audience': ['eco_friendly', 'laundry', 'natural_products', 'sustainability', 'family_safe'],
        'created_at': datetime.now() - timedelta(hours=7),
        'budget_spent': 123.75,
        'impressions': 2876,
        'clicks': 94
    },
    {
        'id': 'ad_045',
        'type': 'advertisement',
        'brand': 'MindfulMoments App',
        'title': 'Find Calm in Your Busy Day',
        'text': 'Personalized meditation and mindfulness app with guided sessions for stress, sleep, and focus. Track your progress, build streaks, join challenges. 14-day free trial.',
        'image': 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
        'cta_text': 'Try Free',
        'cta_link': 'https://mindfulmoments.app/trial',
        'category': 'Health & Wellness',
        'promoted': True,
        'target_audience': ['meditation', 'mindfulness', 'stress_relief', 'mental_health', 'wellness_app'],
        'created_at': datetime.now() - timedelta(hours=19),
        'budget_spent': 189.60,
        'impressions': 4123,
        'clicks': 167
    },
    {
        'id': 'ad_046',
        'type': 'advertisement',
        'brand': 'CareerBoost Resume',
        'title': 'Land Your Dream Job Faster',
        'text': 'Professional resume writing service with ATS optimization. Expert writers, industry-specific templates, LinkedIn profile makeover. 60-day interview guarantee or money back.',
        'image': 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&h=600&fit=crop',
        'cta_text': 'Get Resume',
        'cta_link': 'https://careerboost.com/resume-service',
        'category': 'Professional Services',
        'promoted': True,
        'target_audience': ['resume', 'job_search', 'career_development', 'professional_writing', 'employment'],
        'created_at': datetime.now() - timedelta(hours=3),
        'budget_spent': 234.50,
        'impressions': 4987,
        'clicks': 189
    },
    {
        'id': 'ad_047',
        'type': 'advertisement',
        'brand': 'FlavorFeast Spices',
        'title': 'Spice Up Your Cooking Game',
        'text': 'Premium spice blends and seasonings from around the world. Freshly ground, ethically sourced, chef-approved recipes included. Transform ordinary meals into extraordinary experiences.',
        'image': 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
        'cta_text': 'Explore Spices',
        'cta_link': 'https://flavorfeast.com/spice-collections',
        'category': 'Food & Beverage',
        'promoted': True,
        'target_audience': ['cooking', 'spices', 'gourmet', 'culinary', 'food_enthusiasts'],
        'created_at': datetime.now() - timedelta(hours=10),
        'budget_spent': 167.25,
        'impressions': 3567,
        'clicks': 128
    },
    {
        'id': 'ad_048',
        'type': 'advertisement',
        'brand': 'VitalWatch Health',
        'title': 'Monitor Your Health 24/7',
        'text': 'Advanced fitness tracker with heart rate, sleep tracking, and stress monitoring. Waterproof design, 7-day battery life, smartphone notifications. Your health companion.',
        'image': 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=800&h=600&fit=crop',
        'cta_text': 'Track Health',
        'cta_link': 'https://vitalwatch.com/health-tracker',
        'category': 'Health & Fitness',
        'promoted': True,
        'target_audience': ['fitness_tracker', 'health_monitoring', 'wearable_tech', 'wellness', 'fitness'],
        'created_at': datetime.now() - timedelta(hours=14),
        'budget_spent': 198.80,
        'impressions': 4356,
        'clicks': 156
    },
    {
        'id': 'ad_049',
        'type': 'advertisement',
        'brand': 'CraftBrew Supply Co',
        'title': 'Brew Your Perfect Beer',
        'text': 'Complete homebrewing kits and ingredients for craft beer enthusiasts. Premium malts, hops, and yeast. Step-by-step guides and video tutorials. Join the brewing community today.',
        'image': 'https://images.unsplash.com/photo-1608270586620-248524c67de9?w=800&h=600&fit=crop',
        'cta_text': 'Start Brewing',
        'cta_link': 'https://craftbrewsupply.com/starter-kits',
        'category': 'Food & Beverage',
        'promoted': True,
        'target_audience': ['homebrewing', 'craft_beer', 'diy', 'beer_making', 'brewing_supplies'],
        'created_at': datetime.now() - timedelta(hours=21),
        'budget_spent': 145.35,
        'impressions': 3187,
        'clicks': 109
    },
    {
        'id': 'ad_050',
        'type': 'advertisement',
        'brand': 'StudySpace Pro',
        'title': 'Ace Your Exams with AI',
        'text': 'AI-powered study platform that creates personalized learning plans. Practice tests, flashcards, progress tracking. Proven to improve grades by 40%. Free for students.',
        'image': 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=600&fit=crop',
        'cta_text': 'Study Smarter',
        'cta_link': 'https://studyspace.pro/student-signup',
        'category': 'Education',
        'promoted': True,
        'target_audience': ['studying', 'education', 'exam_prep', 'students', 'ai_learning'],
        'created_at': datetime.now() - timedelta(hours=5),
        'budget_spent': 176.90,
        'impressions': 3892,
        'clicks': 145
    },
    {
        'id': 'ad_051',
        'type': 'advertisement',
        'brand': 'EcoRide Scooters',
        'title': 'Zip Through Traffic Sustainably',
        'text': 'Electric scooters with 40-mile range and 25mph top speed. Foldable design, app connectivity, anti-theft features. Perfect for urban commuting. Try risk-free for 30 days.',
        'image': 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=800&h=600&fit=crop',
        'cta_text': 'Ride Now',
        'cta_link': 'https://ecoride.com/electric-scooters',
        'category': 'Transportation',
        'promoted': True,
        'target_audience': ['electric_scooter', 'urban_mobility', 'eco_friendly', 'commuting', 'sustainable_transport'],
        'created_at': datetime.now() - timedelta(hours=17),
        'budget_spent': 212.45,
        'impressions': 4567,
        'clicks': 173
    },
    {
        'id': 'ad_052',
        'type': 'advertisement',
        'brand': 'LuxuryLinen Bedding',
        'title': 'Sleep in Pure Luxury',
        'text': 'Egyptian cotton bedding with 1000+ thread count. Hotel-quality sheets, pillowcases, and duvet covers. Temperature regulating, hypoallergenic. 100-night sleep trial.',
        'image': 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=800&h=600&fit=crop',
        'cta_text': 'Sleep Better',
        'cta_link': 'https://luxurylinen.com/egyptian-cotton',
        'category': 'Home & Garden',
        'promoted': True,
        'target_audience': ['bedding', 'luxury', 'sleep_quality', 'home_comfort', 'premium_textiles'],
        'created_at': datetime.now() - timedelta(hours=1),
        'budget_spent': 187.70,
        'impressions': 4123,
        'clicks': 158
    }

]
