from datetime import datetime, timedelta
temp_posts = [
    {
        'id': 1,
        'author': 'Sarah Adventure',
        'username': '@sarahadventure',
        'avatar': 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face',
        'title': 'Sunrise Hike at Mount Washington',
        'text': 'Started our hike at 4 AM to catch this incredible sunrise! The 6-mile trek was challenging but absolutely worth it. Nothing beats the feeling of accomplishment when you reach the summit. #MountainLife #Adventure #Hiking',
        'image': 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
        'location': 'Mount Washington, New Hampshire',
        'timestamp': datetime.now() - timedelta(hours=1.500),
        'likes': 247,
        'comments': 23,
        'shares': 12,
        'tags': ['hiking', 'sunrise', 'mountains', 'adventure', 'nature']
    },
    {
        'id': 2,
        'author': 'Marcus Fitlife',
        'username': '@marcusfitlife',
        'avatar': 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
        'title': 'Morning Yoga Session by the Beach',
        'text': 'There\'s something magical about practicing yoga with the sound of waves in the background. Started my day with this 45-minute flow session. Mind, body, and soul aligned! 🧘‍♂️ #YogaLife #BeachYoga #MorningRoutine',
        'image': 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&h=600&fit=crop',
        'location': 'Malibu Beach, California',
        'timestamp': datetime.now() - timedelta(hours=5),
        'likes': 189,
        'comments': 31,
        'shares': 8,
        'tags': ['yoga', 'beach', 'wellness', 'fitness', 'mindfulness']
    },
    {
        'id': 3,
        'author': 'Emma Wanderlust',
        'username': '@emmawanderlust',
        'avatar': 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face',
        'title': 'Exploring the Hidden Waterfalls of Iceland',
        'text': 'Day 3 in Iceland and I discovered this breathtaking hidden waterfall! The 2-hour hike through rugged terrain led us to this pristine natural wonder. Iceland never ceases to amaze me with its raw beauty. #Iceland #Waterfalls #Travel',
        'image': 'https://images.unsplash.com/photo-1539066834862-2d39e7b4e7f9?w=800&h=600&fit=crop',
        'location': 'Westfjords, Iceland',
        'timestamp': datetime.now() - timedelta(hours=8),
        'likes': 412,
        'comments': 67,
        'shares': 28,
        'tags': ['iceland', 'waterfalls', 'travel', 'nature', 'adventure']
    },
    {
        'id': 4,
        'author': 'Jake Strongman',
        'username': '@jakestrongman',
        'avatar': 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
        'title': 'Deadlift PR - 405lbs!',
        'text': 'Finally hit my goal! 405lbs deadlift after 8 months of consistent training. The key was progressive overload and proper form. Remember, strength isn\'t built overnight - it\'s built rep by rep, day by day! 💪 #Deadlift #Strength #Fitness',
        'image': 'https://images.unsplash.com/photo-1571019613914-85e30c978df2?w=800&h=600&fit=crop',
        'location': 'Iron Temple Gym, Austin',
        'timestamp': datetime.now() - timedelta(hours=12),
        'likes': 324,
        'comments': 45,
        'shares': 15,
        'tags': ['deadlift', 'strength', 'fitness', 'gym', 'personalrecord']
    },
    {
        'id': 5,
        'author': 'Luna Explorer',
        'username': '@lunaexplorer',
        'avatar': 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop&crop=face',
        'title': 'Backpacking Through Patagonia',
        'text': 'Week 2 of my solo backpacking adventure through Patagonia. The Torres del Paine circuit has been the highlight so far. Carrying everything you need on your back teaches you what truly matters in life. #Backpacking #Patagonia #Solo Travel',
        'image': 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&h=600&fit=crop',
        'location': 'Torres del Paine, Chile',
        'timestamp': datetime.now() - timedelta(days=1),
        'likes': 567,
        'comments': 89,
        'shares': 34,
        'tags': ['backpacking', 'patagonia', 'solotravel', 'adventure', 'hiking']
    },
    {
        'id': 6,
        'author': 'Maya Wellness',
        'username': '@mayawellness',
        'avatar': 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&h=150&fit=crop&crop=face',
        'title': 'Healthy Meal Prep Sunday',
        'text': 'Spent my Sunday preparing nutritious meals for the week! Grilled chicken, quinoa bowls, roasted vegetables, and fresh fruit. Meal prep is a game-changer for maintaining a healthy lifestyle during busy weekdays. #MealPrep #HealthyEating #Nutrition',
        'image': 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800&h=600&fit=crop',
        'location': 'Home Kitchen',
        'timestamp': datetime.now() - timedelta(days=1, hours=3),
        'likes': 298,
        'comments': 52,
        'shares': 19,
        'tags': ['mealprep', 'healthyeating', 'nutrition', 'wellness', 'lifestyle']
    },
    {
        'id': 7,
        'author': 'Alex Summit',
        'username': '@alexsummit',
        'avatar': 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face',
        'title': 'Rock Climbing in Joshua Tree',
        'text': 'Conquered my first 5.10a route today at Joshua Tree! The desert landscape here is absolutely stunning. Rock climbing pushes you to overcome mental barriers as much as physical ones. Every hold teaches you something new about yourself. #RockClimbing #Joshua Tree',
        'image': 'https://images.unsplash.com/photo-1522163182402-834f871fd851?w=800&h=600&fit=crop',
        'location': 'Joshua Tree National Park, California',
        'timestamp': datetime.now() - timedelta(days=2),
        'likes': 387,
        'comments': 41,
        'shares': 22,
        'tags': ['rockclimbing', 'joshuatree', 'climbing', 'adventure', 'desert']
    },
    {
        'id': 8,
        'author': 'Sofia Runner',
        'username': '@sofiarunner',
        'avatar': 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop&crop=face',
        'title': 'Marathon Training - 20 Mile Long Run',
        'text': 'Completed my longest training run yet - 20 miles! The last 5 miles were pure mental toughness. Training for my first marathon has been an incredible journey of self-discovery. 4 weeks to go! #Marathon #Running #Training',
        'image': 'https://images.unsplash.com/photo-1571008887538-b36bb32f4571?w=800&h=600&fit=crop',
        'location': 'Central Park, New York',
        'timestamp': datetime.now() - timedelta(days=2, hours=6),
        'likes': 445,
        'comments': 78,
        'shares': 31,
        'tags': ['marathon', 'running', 'training', 'fitness', 'endurance']
    },
    {
        'id': 9,
        'author': 'David Oceanic',
        'username': '@davidoceanic',
        'avatar': 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&h=150&fit=crop&crop=face',
        'title': 'Scuba Diving in the Great Barrier Reef',
        'text': 'Diving in the Great Barrier Reef was like entering another world! The biodiversity here is incredible - saw sea turtles, reef sharks, and countless colorful fish species. We must protect these precious ecosystems for future generations. #ScubaDiving #Great Barrier Reef',
        'image': 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&h=600&fit=crop',
        'location': 'Great Barrier Reef, Australia',
        'timestamp': datetime.now() - timedelta(days=3),
        'likes': 623,
        'comments': 94,
        'shares': 47,
        'tags': ['scubadiving', 'greatbarrierreef', 'underwater', 'marine', 'conservation']
    },
    {
        'id': 10,
        'author': 'Taylor Balance',
        'username': '@taylorbalance',
        'avatar': 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=150&h=150&fit=crop&crop=face',
        'title': 'HIIT Workout - 30 Minutes of Intensity',
        'text': 'Just finished an incredible 30-minute HIIT session! Combined cardio and strength training for maximum efficiency. Burpees, mountain climbers, and kettlebell swings - my heart rate is still elevated! Perfect for busy schedules. #HIIT #Workout #Fitness',
        'image': 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=800&h=600&fit=crop',
        'location': 'Fitness First Gym',
        'timestamp': datetime.now() - timedelta(days=3, hours=4),
        'likes': 256,
        'comments': 38,
        'shares': 14,
        'tags': ['hiit', 'workout', 'fitness', 'cardio', 'strength']
    },
    {
        'id': 11,
        'author': 'Rachel Wildness',
        'username': '@rachelwildness',
        'avatar': 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=150&h=150&fit=crop&crop=face',
        'title': 'Wild Camping in the Scottish Highlands',
        'text': 'Pitched my tent under the stars in the remote Scottish Highlands. No phone signal, no distractions - just me, nature, and the sound of the wind. Sometimes you need to disconnect to truly reconnect with yourself. 🏕️ #WildCamping #Scotland',
        'image': 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800&h=600&fit=crop',
        'location': 'Isle of Skye, Scotland',
        'timestamp': datetime.now() - timedelta(days=4),
        'likes': 398,
        'comments': 56,
        'shares': 23,
        'tags': ['wildcamping', 'scotland', 'highlands', 'camping', 'nature']
    },
    {
        'id': 12,
        'author': 'Kevin Strength',
        'username': '@kevinstrength',
        'avatar': 'https://images.unsplash.com/photo-1566492031773-4f4e44671d66?w=150&h=150&fit=crop&crop=face',
        'title': 'Calisthenics in the Park - Bodyweight Mastery',
        'text': 'Who needs a gym when you have a pull-up bar and gravity? Spent the morning working on muscle-ups and human flags. Calisthenics teaches you to master your own bodyweight and builds incredible functional strength. #Calisthenics #BodyweightTraining',
        'image': 'https://images.unsplash.com/photo-1571019613914-85e30c978df2?w=800&h=600&fit=crop',
        'location': 'Central Park, NYC',
        'timestamp': datetime.now() - timedelta(days=4, hours=3),
        'likes': 278,
        'comments': 34,
        'shares': 18,
        'tags': ['calisthenics', 'bodyweight', 'fitness', 'strength', 'park']
    },
    {
        'id': 13,
        'author': 'Nina Wanderer',
        'username': '@ninawanderer',
        'avatar': 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=150&h=150&fit=crop&crop=face',
        'title': 'Sunrise Hot Air Balloon Over Cappadocia',
        'text': 'Floating above the fairy chimneys of Cappadocia at sunrise was pure magic! The landscape looked like another planet. This bucket list experience reminded me why I love to travel - for moments that take your breath away. ✨ #Cappadocia #HotAirBalloon',
        'image': 'https://images.unsplash.com/photo-1464207687429-7505649dae38?w=800&h=600&fit=crop',
        'location': 'Cappadocia, Turkey',
        'timestamp': datetime.now() - timedelta(days=5),
        'likes': 712,
        'comments': 98,
        'shares': 67,
        'tags': ['cappadocia', 'hotairballoon', 'sunrise', 'turkey', 'bucketlist']
    },
    {
        'id': 14,
        'author': 'Carlos Cyclist',
        'username': '@carloscyclist',
        'avatar': 'https://images.unsplash.com/photo-1552374196-c4e7ffc6e126?w=150&h=150&fit=crop&crop=face',
        'title': '100-Mile Century Ride Complete!',
        'text': 'Just completed my first century ride - 100 miles through the rolling hills of Napa Valley! The last 20 miles were brutal but crossing that finish line was incredible. Cycling teaches you that your mind gives up long before your body does. 🚴‍♂️ #CenturyRide #Cycling',
        'image': 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop',
        'location': 'Napa Valley, California',
        'timestamp': datetime.now() - timedelta(days=5, hours=6),
        'likes': 445,
        'comments': 72,
        'shares': 29,
        'tags': ['cycling', 'centuryride', 'napavalley', 'endurance', 'biking']
    },
    {
        'id': 15,
        'author': 'Zoe Aquatic',
        'username': '@zoeaquatic',
        'avatar': 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&h=150&fit=crop&crop=face',
        'title': 'Swimming with Whale Sharks in the Maldives',
        'text': 'Today I swam alongside the gentle giants of the ocean - whale sharks! These magnificent creatures are completely harmless and swimming next to something so massive yet graceful was humbling. Protecting our oceans has never felt more important. 🦈 #WhaleShark #Maldives',
        'image': 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&h=600&fit=crop',
        'location': 'South Ari Atoll, Maldives',
        'timestamp': datetime.now() - timedelta(days=6),
        'likes': 834,
        'comments': 156,
        'shares': 94,
        'tags': ['whaleshark', 'maldives', 'swimming', 'ocean', 'marine']
    },
    {
        'id': 16,
        'author': 'Omar Mindful',
        'username': '@omarmindful',
        'avatar': 'https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=150&h=150&fit=crop&crop=face',
        'title': 'Silent Meditation Retreat - Day 5',
        'text': 'Five days into my silent meditation retreat in the mountains. No talking, no phones, just being present with my thoughts. The mental clarity I\'m gaining is incredible. Sometimes the greatest adventure is the journey inward. 🧘‍♂️ #Meditation #Mindfulness #Retreat',
        'image': 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
        'location': 'Dharamshala, India',
        'timestamp': datetime.now() - timedelta(days=6, hours=8),
        'likes': 367,
        'comments': 89,
        'shares': 45,
        'tags': ['meditation', 'mindfulness', 'retreat', 'dharamshala', 'silence']
    },
    {
        'id': 17,
        'author': 'Isabella Climber',
        'username': '@isabellaclimber',
        'avatar': 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=150&h=150&fit=crop&crop=face',
        'title': 'Ice Climbing in the Canadian Rockies',
        'text': 'Conquered my first ice climbing route today! The frozen waterfalls of the Canadian Rockies are absolutely stunning. Ice climbing is a completely different beast from rock climbing - it\'s all about technique, patience, and trusting your tools. ❄️ #IceClimbing #CanadianRockies',
        'image': 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=800&h=600&fit=crop',
        'location': 'Banff National Park, Canada',
        'timestamp': datetime.now() - timedelta(days=7),
        'likes': 523,
        'comments': 67,
        'shares': 38,
        'tags': ['iceclimbing', 'banff', 'canadianrockies', 'winter', 'climbing']
    },
    {
        'id': 18,
        'author': 'Liam Nutrition',
        'username': '@liamnutrition',
        'avatar': 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&h=150&fit=crop&crop=face',
        'title': 'Plant-Based Protein Bowl Recipe',
        'text': 'Who says you can\'t get enough protein on a plant-based diet? This bowl has 35g of protein: quinoa, hemp seeds, chickpeas, and tahini dressing. Fueling my body with whole foods has completely transformed my energy levels and recovery! 🌱 #PlantBased #Nutrition #ProteinBowl',
        'image': 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&h=600&fit=crop',
        'location': 'Home Kitchen',
        'timestamp': datetime.now() - timedelta(days=7, hours=4),
        'likes': 289,
        'comments': 48,
        'shares': 31,
        'tags': ['plantbased', 'nutrition', 'protein', 'healthy', 'vegan']
    },
    {
        'id': 19,
        'author': 'Phoenix Surfer',
        'username': '@phoenixsurfer',
        'avatar': 'https://images.unsplash.com/photo-1463453091185-61582044d556?w=150&h=150&fit=crop&crop=face',
        'title': 'Dawn Patrol Surfing in Bali',
        'text': 'Caught the most perfect waves this morning at Uluwatu! Dawn patrol sessions are my favorite - empty lineups, glassy water, and that golden morning light. Bali never disappoints. The ocean is my church and surfing is my prayer. 🏄‍♀️ #Surfing #Bali #DawnPatrol',
        'image': 'https://images.unsplash.com/photo-1502680390469-be75c86b636f?w=800&h=600&fit=crop',
        'location': 'Uluwatu, Bali',
        'timestamp': datetime.now() - timedelta(days=8),
        'likes': 678,
        'comments': 134,
        'shares': 56,
        'tags': ['surfing', 'bali', 'uluwatu', 'dawnpatrol', 'waves']
    },
    {
        'id': 20,
        'author': 'Ava Crossfit',
        'username': '@avacrossfit',
        'avatar': 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face',
        'title': 'CrossFit Competition - First Place!',
        'text': 'WON MY FIRST CROSSFIT COMPETITION! 🏆 Six months of intense training paid off. The final WOD was brutal: 100 burpees, 200 double-unders, and a 1-mile run. My legs are jello but my heart is full. Grateful for this amazing community that pushes me every day! #CrossFit #Competition',
        'image': 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&h=600&fit=crop',
        'location': 'CrossFit Central, Denver',
        'timestamp': datetime.now() - timedelta(days=8, hours=7),
        'likes': 567,
        'comments': 98,
        'shares': 43,
        'tags': ['crossfit', 'competition', 'firstplace', 'training', 'community']
    },
    {
        'id': 21,
        'author': 'Tyler Trekker',
        'username': '@tylertrekker',
        'avatar': 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&h=150&fit=crop&crop=face',
        'title': 'Everest Base Camp - Day 12',
        'text': 'Finally reached Everest Base Camp after 12 days of trekking! The altitude is brutal but the views are otherworldly. Standing here at 17,598 feet, looking at the world\'s tallest mountain, I feel so small yet so grateful. This journey has pushed me beyond my limits. ⛰️ #EverestBaseCamp #Trekking',
        'image': 'https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=800&h=600&fit=crop',
        'location': 'Everest Base Camp, Nepal',
        'timestamp': datetime.now() - timedelta(days=9),
        'likes': 923,
        'comments': 187,
        'shares': 89,
        'tags': ['everest', 'basecamp', 'trekking', 'nepal', 'mountains']
    },
    {
        'id': 22,
        'author': 'Mia Swimmer',
        'username': '@miaswimmer',
        'avatar': 'https://images.unsplash.com/photo-1525134479668-1bee5c7c6845?w=150&h=150&fit=crop&crop=face',
        'title': 'Open Water Swimming - Lake Tahoe',
        'text': 'Completed a 5-mile open water swim across Lake Tahoe today! The crystal clear alpine water was freezing but absolutely beautiful. Open water swimming is meditation in motion - just you, the water, and your rhythm. No black lines, no walls, just pure freedom! 🏊‍♀️ #OpenWater #Swimming',
        'image': 'https://images.unsplash.com/photo-1530549387789-4c1017266635?w=800&h=600&fit=crop',
        'location': 'Lake Tahoe, California',
        'timestamp': datetime.now() - timedelta(days=9, hours=5),
        'likes': 412,
        'comments': 63,
        'shares': 27,
        'tags': ['openwater', 'swimming', 'laketahoe', 'endurance', 'alpine']
    },
    {
        'id': 23,
        'author': 'Diego Desert',
        'username': '@diegodesert',
        'avatar': 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&h=150&fit=crop&crop=face',
        'title': 'Sandboarding the Sahara Dunes',
        'text': 'Spent the day sandboarding down massive dunes in the Sahara Desert! It\'s like snowboarding but with sand that gets EVERYWHERE. The sunset over the endless dunes was absolutely magical. Sometimes the best adventures are the ones that seem impossible. 🏂 #Sandboarding #Sahara #Desert',
        'image': 'https://images.unsplash.com/photo-1539650116574-75c0c6d0327a?w=800&h=600&fit=crop',
        'location': 'Erg Chebbi, Morocco',
        'timestamp': datetime.now() - timedelta(days=10),
        'likes': 567,
        'comments': 78,
        'shares': 42,
        'tags': ['sandboarding', 'sahara', 'morocco', 'desert', 'adventure']
    },
    {
        'id': 24,
        'author': 'Grace Gymnastics',
        'username': '@gracegymnastics',
        'avatar': 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face',
        'title': 'Adult Gymnastics - Never Too Late!',
        'text': 'Started learning gymnastics at 28 and finally nailed my first back handspring! People said I was too old but age is just a number. Your body is capable of amazing things when you believe in yourself and practice consistently. Flexibility and strength have no expiration date! 🤸‍♀️ #AdultGymnastics #Flexibility',
        'image': 'https://images.unsplash.com/photo-1571019613914-85e30c978df2?w=800&h=600&fit=crop',
        'location': 'Elite Gymnastics Center',
        'timestamp': datetime.now() - timedelta(days=10, hours=8),
        'likes': 389,
        'comments': 156,
        'shares': 67,
        'tags': ['gymnastics', 'adult', 'flexibility', 'nevertoolate', 'backhandspring']
    },
    {
        'id': 25,
        'author': 'Finn Fisher',
        'username': '@finnfisher',
        'avatar': 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
        'title': 'Fly Fishing in Patagonian Rivers',
        'text': 'Spent the morning fly fishing in pristine Patagonian rivers. Caught and released several beautiful trout while surrounded by snow-capped peaks. There\'s something deeply meditative about the rhythm of casting and the patience required. Nature provides the best therapy. 🎣 #FlyFishing #Patagonia',
        'image': 'https://images.unsplash.com/photo-1445264718944-b4bf4b7cc58a?w=800&h=600&fit=crop',
        'location': 'Rio Grande, Argentina',
        'timestamp': datetime.now() - timedelta(days=11),
        'likes': 298,
        'comments': 34,
        'shares': 19,
        'tags': ['flyfishing', 'patagonia', 'trout', 'rivers', 'meditation']
    },
    {
        'id': 26,
        'author': 'Aria Athlete',
        'username': '@ariaathlete',
        'avatar': 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face',
        'title': 'Triathlon Training - Brick Workout',
        'text': 'Crushed a bike-to-run brick workout today! 40-mile bike ride immediately followed by a 10k run. Brick workouts are brutal but essential for triathlon training - they teach your legs how to run on jelly! Ironman prep is no joke but I\'m loving the challenge. 🚴‍♀️🏃‍♀️ #Triathlon #BrickWorkout',
        'image': 'https://images.unsplash.com/photo-1571019613914-85e30c978df2?w=800&h=600&fit=crop',
        'location': 'Mission Bay, San Diego',
        'timestamp': datetime.now() - timedelta(days=11, hours=6),
        'likes': 445,
        'comments': 67,
        'shares': 28,
        'tags': ['triathlon', 'brickworkout', 'ironman', 'cycling', 'running']
    },
    {
        'id': 27,
        'author': 'Leo Longitude',
        'username': '@leolongitude',
        'avatar': 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
        'title': 'Northern Lights in Finnish Lapland',
        'text': 'The Aurora Borealis danced across the sky tonight in Finnish Lapland! Stood outside in -30°C weather for 3 hours waiting for this moment. The green curtains of light were absolutely mesmerizing. Some experiences are worth freezing for! ✨ #NorthernLights #Finland #Aurora',
        'image': 'https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=800&h=600&fit=crop',
        'location': 'Rovaniemi, Finland',
        'timestamp': datetime.now() - timedelta(days=12),
        'likes': 789,
        'comments': 134,
        'shares': 78,
        'tags': ['northernlights', 'aurora', 'finland', 'lapland', 'winter']
    },
    {
        'id': 28,
        'author': 'Sage Stretching',
        'username': '@sagestretching',
        'avatar': 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&h=150&fit=crop&crop=face',
        'title': 'Daily Mobility Routine - Game Changer!',
        'text': 'Been doing this 20-minute mobility routine every morning for 3 months and the difference is incredible! My hip flexors, shoulders, and ankles feel amazing. We spend so much time sitting - our bodies crave movement and stretching. Mobility is longevity! 🧘‍♀️ #Mobility #Stretching #Wellness',
        'image': 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&h=600&fit=crop',
        'location': 'Home Studio',
        'timestamp': datetime.now() - timedelta(days=12, hours=4),
        'likes': 234,
        'comments': 45,
        'shares': 32,
        'tags': ['mobility', 'stretching', 'wellness', 'routine', 'flexibility']
    },
    {
        'id': 29,
        'author': 'Kai Kayaker',
        'username': '@kaikayaker',
        'avatar': 'https://images.unsplash.com/photo-1566492031773-4f4e44671d66?w=150&h=150&fit=crop&crop=face',
        'title': 'Sea Kayaking Through Norwegian Fjords',
        'text': 'Paddled through the stunning Geirangerfjord today! The towering waterfalls, steep cliffs, and emerald water created the most epic natural cathedral. Sea kayaking gives you a unique perspective - you\'re part of the landscape, not just observing it. Norway is pure magic! 🛶 #SeaKayaking #Norway #Fjords',
        'image': 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
        'location': 'Geirangerfjord, Norway',
        'timestamp': datetime.now() - timedelta(days=13),
        'likes': 634,
        'comments': 89,
        'shares': 51,
        'tags': ['seakayaking', 'norway', 'fjords', 'geiranger', 'waterfalls']
    },
    {
        'id': 30,
        'author': 'Zara Zen',
        'username': '@zarazen',
        'avatar': 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop&crop=face',
        'title': 'Cold Plunge Therapy - Mental Resilience',
        'text': 'Day 30 of daily cold plunges in 38°F water! What started as physical therapy has become mental training. Those first 30 seconds are pure panic, then your nervous system adapts and you find calm in the chaos. Cold exposure teaches you that discomfort is temporary. 🧊 #ColdPlunge #WimHof #MentalResilience',
        'image': 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&h=600&fit=crop',
        'location': 'Lake Crescent, Washington',
        'timestamp': datetime.now() - timedelta(days=13, hours=7),
        'likes': 467,
        'comments': 98,
        'shares': 43,
        'tags': ['coldplunge', 'wimhof', 'coldtherapy', 'resilience', 'mindset']
    }, {
        'id': 31,
        'author': 'River Rapids',
        'username': '@riverrapids',
        'avatar': 'https://images.unsplash.com/photo-1552374196-c4e7ffc6e126?w=150&h=150&fit=crop&crop=face',
        'title': 'White Water Rafting Class V Rapids',
        'text': 'Conquered the most intense white water rapids of my life today! Class V rapids on the Futaleufú River in Chile - pure adrenaline and teamwork. When you\'re navigating 15-foot waves, there\'s no room for fear, only focus and trust in your crew. What an incredible rush! 🚣‍♂️ #WhiteWaterRafting #Chile',
        'image': 'https://images.unsplash.com/photo-1544966503-7cc532d5a35a?w=800&h=600&fit=crop',
        'location': 'Futaleufú River, Chile',
        'timestamp': datetime.now() - timedelta(days=14),
        'likes': 589,
        'comments': 87,
        'shares': 34,
        'tags': ['whitewaterrafting', 'chile', 'futaleufu', 'rapids', 'adrenaline']
    },
    {
        'id': 32,
        'author': 'Nora Nutrition',
        'username': '@noranutrition',
        'avatar': 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&h=150&fit=crop&crop=face',
        'title': 'Intermittent Fasting - 6 Month Results',
        'text': 'Six months of 16:8 intermittent fasting and I feel incredible! Improved energy, better sleep, and mental clarity like never before. It\'s not about restriction - it\'s about giving your digestive system a break and optimizing when you fuel your body. Consistency is everything! ⏰ #IntermittentFasting #Wellness',
        'image': 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800&h=600&fit=crop',
        'location': 'Home Kitchen',
        'timestamp': datetime.now() - timedelta(days=14, hours=3),
        'likes': 324,
        'comments': 156,
        'shares': 89,
        'tags': ['intermittentfasting', 'wellness', 'nutrition', 'health', 'lifestyle']
    },
    {
        'id': 33,
        'author': 'Atlas Adventure',
        'username': '@atlasadventure',
        'avatar': 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face',
        'title': 'Volcano Hiking in Guatemala',
        'text': 'Hiked up Volcán de Acatenango to watch Volcán de Fuego erupt! Camping at 13,000 feet with an active volcano as your nightlight is surreal. Every 15 minutes, Fuego would explode with lava and ash - nature\'s most powerful fireworks show! 🌋 #VolcanoHiking #Guatemala #Acatenango',
        'image': 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
        'location': 'Volcán de Acatenango, Guatemala',
        'timestamp': datetime.now() - timedelta(days=15),
        'likes': 712,
        'comments': 134,
        'shares': 67,
        'tags': ['volcano', 'guatemala', 'acatenango', 'hiking', 'eruption']
    },
    {
        'id': 34,
        'author': 'Blaze Boxer',
        'username': '@blazeboxer',
        'avatar': 'https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=150&h=150&fit=crop&crop=face',
        'title': 'Boxing Training - Sparring Session',
        'text': 'Intense sparring session today! 8 rounds with different partners really tested my endurance and technique. Boxing teaches you so much about yourself - how to stay calm under pressure, how to think strategically while exhausted. The sweet science never gets old! 🥊 #Boxing #Sparring #Training',
        'image': 'https://images.unsplash.com/photo-1571019613914-85e30c978df2?w=800&h=600&fit=crop',
        'location': 'Iron Fist Boxing Gym',
        'timestamp': datetime.now() - timedelta(days=15, hours=6),
        'likes': 398,
        'comments': 52,
        'shares': 23,
        'tags': ['boxing', 'sparring', 'training', 'sweetscience', 'fitness']
    },
    {
        'id': 35,
        'author': 'Luna Latitude',
        'username': '@lunalatitude',
        'avatar': 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=150&h=150&fit=crop&crop=face',
        'title': 'Solo Female Travel - Salar de Uyuni',
        'text': 'Standing on the world\'s largest salt flat in Bolivia! The mirror effect during sunrise made it feel like walking on clouds. Solo female travel has taught me that the world is much kinder than we\'re told. Trust yourself, trust others, and amazing things happen! ✨ #SoloTravel #SalarDeUyuni #Bolivia',
        'image': 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
        'location': 'Salar de Uyuni, Bolivia',
        'timestamp': datetime.now() - timedelta(days=16),
        'likes': 834,
        'comments': 167,
        'shares': 92,
        'tags': ['solotravel', 'bolivia', 'salardeuyuni', 'saltflats', 'femaletravel']
    },
    {
        'id': 36,
        'author': 'Max Mindset',
        'username': '@maxmindset',
        'avatar': 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
        'title': 'Strongman Training - Atlas Stones',
        'text': 'PR day with Atlas stones! Finally lifted the 300lb stone to shoulder height. Strongman training is humbling - it\'s not just about muscle, it\'s about technique, timing, and mental fortitude. Every rep teaches you something new about leveraging your body\'s power! 💪 #Strongman #AtlasStones #Strength',
        'image': 'https://images.unsplash.com/photo-1571019613914-85e30c978df2?w=800&h=600&fit=crop',
        'location': 'Beast Strength Gym',
        'timestamp': datetime.now() - timedelta(days=16, hours=4),
        'likes': 456,
        'comments': 78,
        'shares': 31,
        'tags': ['strongman', 'atlasstones', 'strength', 'powerlifting', 'pr']
    },
    {
        'id': 37,
        'author': 'Ivy Islands',
        'username': '@ivyislands',
        'avatar': 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=150&h=150&fit=crop&crop=face',
        'title': 'Island Hopping in the Philippines',
        'text': 'Explored hidden lagoons and pristine beaches in Palawan today! Crystal clear turquoise water, limestone cliffs, and not another soul in sight. Island hopping in the Philippines feels like discovering paradise on repeat. Every island has its own magic! 🏝️ #Philippines #Palawan #IslandHopping',
        'image': 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
        'location': 'El Nido, Palawan, Philippines',
        'timestamp': datetime.now() - timedelta(days=17),
        'likes': 723,
        'comments': 98,
        'shares': 54,
        'tags': ['philippines', 'palawan', 'elnido', 'islandhopping', 'paradise']
    },
    {
        'id': 38,
        'author': 'Quinn Quest',
        'username': '@quinnquest',
        'avatar': 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&h=150&fit=crop&crop=face',
        'title': 'Obstacle Course Racing - Spartan Beast',
        'text': 'Conquered the Spartan Beast - 13 miles and 30 obstacles of pure grit! Rope climbs, spear throws, heavy carries, and barbed wire crawls. OCR teaches you that physical strength means nothing without mental resilience. Every burpee penalty was earned and worth it! 🏃‍♂️ #SpartanRace #OCR #Beast',
        'image': 'https://images.unsplash.com/photo-1571019613914-85e30c978df2?w=800&h=600&fit=crop',
        'location': 'Tahoe Vista, California',
        'timestamp': datetime.now() - timedelta(days=17, hours=7),
        'likes': 567,
        'comments': 89,
        'shares': 45,
        'tags': ['spartanrace', 'ocr', 'obstaclerace', 'beast', 'endurance']
    },
    {
        'id': 39,
        'author': 'Serena Summit',
        'username': '@serenasummit',
        'avatar': 'https://images.unsplash.com/photo-1525134479668-1bee5c7c6845?w=150&h=150&fit=crop&crop=face',
        'title': 'Alpaca Trekking in the Andes',
        'text': 'Spent the day trekking with alpacas through the Peruvian Andes! These gentle creatures are the perfect hiking companions - they carry your gear and provide endless entertainment. The ancient Inca trails combined with alpaca therapy made for one unforgettable day! 🦙 #AlpacaTrekking #Peru #Andes',
        'image': 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
        'location': 'Sacred Valley, Peru',
        'timestamp': datetime.now() - timedelta(days=18),
        'likes': 645,
        'comments': 123,
        'shares': 67,
        'tags': ['alpaca', 'peru', 'andes', 'trekking', 'sacredvalley']
    },
    {
        'id': 40,
        'author': 'Dex Dynamic',
        'username': '@dexdynamic',
        'avatar': 'https://images.unsplash.com/photo-1566492031773-4f4e44671d66?w=150&h=150&fit=crop&crop=face',
        'title': 'Parkour Training - Urban Movement',
        'text': 'Spent the afternoon flowing through the city with parkour! Vaulting benches, precision jumps, and wall runs turn the urban environment into your playground. Parkour teaches you to see obstacles as opportunities and movement as art. The city is your gym! 🏃‍♂️ #Parkour #UrbanMovement #Flow',
        'image': 'https://images.unsplash.com/photo-1571019613914-85e30c978df2?w=800&h=600&fit=crop',
        'location': 'Downtown Portland',
        'timestamp': datetime.now() - timedelta(days=18, hours=5),
        'likes': 389,
        'comments': 67,
        'shares': 29,
        'tags': ['parkour', 'urbanmovement', 'flow', 'freerunning', 'movement']
    },
    {
        'id': 41,
        'author': 'Storm Skipper',
        'username': '@stormskipper',
        'avatar': 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&h=150&fit=crop&crop=face',
        'title': 'Backcountry Skiing in the Alps',
        'text': 'Earned my turns today with a 6-hour backcountry ski tour in Chamonix! Fresh powder, untouched slopes, and the most incredible mountain views. Backcountry skiing is meditation in motion - every turn connects you deeper with the mountain. Pure alpine bliss! ⛷️ #BackcountrySki #Chamonix #Alps',
        'image': 'https://images.unsplash.com/photo-1551524164-6cf96ac6d5c5?w=800&h=600&fit=crop',
        'location': 'Chamonix, France',
        'timestamp': datetime.now() - timedelta(days=19),
        'likes': 678,
        'comments': 94,
        'shares': 48,
        'tags': ['backcountryski', 'chamonix', 'alps', 'powder', 'skiing']
    },
    {
        'id': 42,
        'author': 'Violet Vitality',
        'username': '@violetvitality',
        'avatar': 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&h=150&fit=crop&crop=face',
        'title': 'Breathwork Session - Wim Hof Method',
        'text': 'Completed my first Wim Hof breathwork session today! 3 rounds of controlled hyperventilation followed by breath retention. The tingling sensations and mental clarity were incredible. Amazing how something as simple as breathing can unlock such powerful states of consciousness! 🫁 #WimHof #Breathwork #Consciousness',
        'image': 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&h=600&fit=crop',
        'location': 'Meditation Studio',
        'timestamp': datetime.now() - timedelta(days=19, hours=4),
        'likes': 423,
        'comments': 87,
        'shares': 56,
        'tags': ['wimhof', 'breathwork', 'meditation', 'consciousness', 'wellness']
    },
    {
        'id': 43,
        'author': 'Rex Rover',
        'username': '@rexrover',
        'avatar': 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
        'title': 'Overlanding Through the Sahara',
        'text': 'Day 12 of overlanding across the Sahara Desert in Morocco! Our 4x4 has been our home, carrying everything we need for this epic journey. Sleeping under a blanket of stars with zero light pollution - the Milky Way has never looked so bright! 🚙 #Overlanding #Sahara #Morocco #DesertLife',
        'image': 'https://images.unsplash.com/photo-1539650116574-75c0c6d0327a?w=800&h=600&fit=crop',
        'location': 'Sahara Desert, Morocco',
        'timestamp': datetime.now() - timedelta(days=20),
        'likes': 734,
        'comments': 112,
        'shares': 63,
        'tags': ['overlanding', 'sahara', 'morocco', 'desert', 'stars']
    },
    {
        'id': 44,
        'author': 'Jade Jumper',
        'username': '@jadejumper',
        'avatar': 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face',
        'title': 'Bungee Jumping - 764 Feet Drop!',
        'text': 'Just bungee jumped off the Macau Tower - 764 feet of pure terror and exhilaration! Those 5 seconds of freefall felt like a lifetime. Sometimes you need to literally jump into your fears to discover what you\'re truly capable of. Adrenaline is the best drug! 🪂 #BungeeJump #Macau #Adrenaline',
        'image': 'https://images.unsplash.com/photo-1544966503-7cc532d5a35a?w=800&h=600&fit=crop',
        'location': 'Macau Tower, China',
        'timestamp': datetime.now() - timedelta(days=20, hours=6),
        'likes': 892,
        'comments': 178,
        'shares': 89,
        'tags': ['bungeejump', 'macau', 'adrenaline', 'freefall', 'fearless']
    },
    {
        'id': 45,
        'author': 'Echo Endurance',
        'username': '@echoendurance',
        'avatar': 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop&crop=face',
        'title': 'Ultra Marathon - 50K Trail Run',
        'text': 'Finished my first 50K ultra marathon on mountain trails! 31 miles of pure grit through elevation changes, river crossings, and technical terrain. Around mile 25 my body wanted to quit but my mind kept pushing. Ultra running teaches you that limits are mostly mental! 🏃‍♀️ #UltraMarathon #TrailRunning #50K',
        'image': 'https://images.unsplash.com/photo-1571008887538-b36bb32f4571?w=800&h=600&fit=crop',
        'location': 'Mount Wilson Trail, California',
        'timestamp': datetime.now() - timedelta(days=21),
        'likes': 567,
        'comments': 134,
        'shares': 67,
        'tags': ['ultramarathon', 'trailrunning', '50k', 'endurance', 'mountains']
    },
    {
        'id': 46,
        'author': 'Nova Navigator',
        'username': '@novanavigator',
        'avatar': 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face',
        'title': 'Sailing Solo Across the Pacific',
        'text': 'Day 18 of my solo Pacific crossing! Nothing but ocean in every direction for the past week. Sailing alone teaches you self-reliance like nothing else - you\'re navigator, mechanic, and captain all in one. The sunsets out here are absolutely magical! ⛵ #SoloSailing #Pacific #Ocean #Adventure',
        'image': 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
        'location': 'Pacific Ocean',
        'timestamp': datetime.now() - timedelta(days=21, hours=8),
        'likes': 645,
        'comments': 89,
        'shares': 45,
        'tags': ['solosailing', 'pacific', 'ocean', 'sailing', 'sunset']
    },
    {
        'id': 47,
        'author': 'Axel Action',
        'username': '@axelaction',
        'avatar': 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face',
        'title': 'Muay Thai Training in Thailand',
        'text': 'Week 3 of intensive Muay Thai training in Bangkok! 6 hours daily of technique, sparring, and conditioning. Training with authentic Thai fighters has been humbling and inspiring. The art of eight limbs is as much about respect and discipline as it is combat! 🥊 #MuayThai #Thailand #MartialArts',
        'image': 'https://images.unsplash.com/photo-1571019613914-85e30c978df2?w=800&h=600&fit=crop',
        'location': 'Lumpinee Stadium, Bangkok',
        'timestamp': datetime.now() - timedelta(days=22),
        'likes': 489,
        'comments': 76,
        'shares': 32,
        'tags': ['muaythai', 'thailand', 'bangkok', 'martialarts', 'training']
    },
    {
        'id': 48,
        'author': 'Sage Serenity',
        'username': '@sageserenity',
        'avatar': 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop&crop=face',
        'title': 'Forest Bathing - Japanese Shinrin-yoku',
        'text': 'Practiced shinrin-yoku (forest bathing) in the ancient redwoods today. No phones, no agenda - just mindful presence among these 1000-year-old giants. Scientific studies show forest bathing reduces cortisol and boosts immunity. Nature really is the best medicine! 🌲 #ForestBathing #Shinrinyoku #Mindfulness',
        'image': 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
        'location': 'Muir Woods, California',
        'timestamp': datetime.now() - timedelta(days=22, hours=5),
        'likes': 378,
        'comments': 67,
        'shares': 43,
        'tags': ['forestbathing', 'shinrinyoku', 'mindfulness', 'redwoods', 'nature']
    },
    {
        'id': 49,
        'author': 'Rio Rush',
        'username': '@riorush',
        'avatar': 'https://images.unsplash.com/photo-1552374196-c4e7ffc6e126?w=150&h=150&fit=crop&crop=face',
        'title': 'Canyoneering in Zion National Park',
        'text': 'Descended through the Narrows slot canyon in Zion! Rappelling down waterfalls, swimming through pools, and squeezing through gaps barely wider than my body. Canyoneering combines technical skills with pure adventure - every turn reveals new wonders carved by millions of years of water! 🏔️ #Canyoneering #Zion #SlotCanyon',
        'image': 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
        'location': 'Zion National Park, Utah',
        'timestamp': datetime.now() - timedelta(days=23),
        'likes': 623,
        'comments': 98,
        'shares': 51,
        'tags': ['canyoneering', 'zion', 'slotcanyon', 'rappelling', 'adventure']
    },
    {
        'id': 50,
        'author': 'Bliss Balance',
        'username': '@blissbalance',
        'avatar': 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&h=150&fit=crop&crop=face',
        'title': 'Functional Movement Screen - Injury Prevention',
        'text': 'Completed a comprehensive functional movement screen today! Identified some imbalances in my hip mobility and shoulder stability. Prevention is always better than rehabilitation. Taking time to assess and correct movement patterns is investment in long-term health and performance! 🔄 #FunctionalMovement #InjuryPrevention #Mobility',
        'image': 'https://images.unsplash.com/photo-1571019613914-85e30c978df2?w=800&h=600&fit=crop',
        'location': 'Performance Therapy Center',
        'timestamp': datetime.now() - timedelta(days=23, hours=7),
        'likes': 234,
        'comments': 45,
        'shares': 28,
        'tags': ['functionalmovement', 'injuryprevention', 'mobility', 'assessment', 'health']
    }, {
        'id': 51,
        'author': 'Falcon Freeride',
        'username': '@falconfreeride',
        'avatar': 'https://images.unsplash.com/photo-1566492031773-4f4e44671d66?w=150&h=150&fit=crop&crop=face',
        'title': 'Heli-Skiing in British Columbia',
        'text': 'Dropped into virgin powder via helicopter in the Canadian Rockies! 3,000 vertical feet of untouched snow and not another soul for miles. Heli-skiing is the ultimate luxury - earning your turns by helicopter and skiing terrain most people only dream of! ❄️ #HeliSkiing #BritishColumbia #PowderDays',
        'image': 'https://images.unsplash.com/photo-1551524164-6cf96ac6d5c5?w=800&h=600&fit=crop',
        'location': 'Whistler, British Columbia',
        'timestamp': datetime.now() - timedelta(days=24),
        'likes': 789,
        'comments': 123,
        'shares': 67,
        'tags': ['heliskiing', 'britishcolumbia', 'powder', 'whistler', 'skiing']
    },
    {
        'id': 52,
        'author': 'Maya Mobility',
        'username': '@mayamobility',
        'avatar': 'https://images.unsplash.com/photo-1525134479668-1bee5c7c6845?w=150&h=150&fit=crop&crop=face',
        'title': 'Aerial Yoga - Defying Gravity',
        'text': 'Discovered aerial yoga and I\'m completely hooked! Hanging upside down in silk hammocks while doing poses feels like flying. The inversions decompress your spine naturally and the core engagement is incredible. Who knew yoga could make you feel like a circus performer! 🤸‍♀️ #AerialYoga #AntiGravity #Yoga',
        'image': 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&h=600&fit=crop',
        'location': 'Zen Flow Studio',
        'timestamp': datetime.now() - timedelta(days=24, hours=3),
        'likes': 445,
        'comments': 78,
        'shares': 34,
        'tags': ['aerialyoga', 'antigravity', 'yoga', 'inversions', 'flexibility']
    },
    {
        'id': 53,
        'author': 'Phoenix Explorer',
        'username': '@phoenixexplorer',
        'avatar': 'https://images.unsplash.com/photo-1463453091185-61582044d556?w=150&h=150&fit=crop&crop=face',
        'title': 'Cave Diving in the Yucatan Cenotes',
        'text': 'Dove into the crystal-clear cenotes of Mexico today! These underwater cave systems are like cathedrals beneath the earth. Swimming through limestone tunnels with perfect visibility and ancient stalactites is otherworldly. Cave diving requires advanced skills but the rewards are magical! 🤿 #CaveDiving #Cenotes #Mexico',
        'image': 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&h=600&fit=crop',
        'location': 'Tulum, Quintana Roo, Mexico',
        'timestamp': datetime.now() - timedelta(days=25),
        'likes': 612,
        'comments': 89,
        'shares': 45,
        'tags': ['cavediving', 'cenotes', 'mexico', 'tulum', 'underwater']
    },
    {
        'id': 54,
        'author': 'Atlas Athlete',
        'username': '@atlasathlete',
        'avatar': 'https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=150&h=150&fit=crop&crop=face',
        'title': 'Kettlebell Sport - 24kg Long Cycle',
        'text': 'Completed my first kettlebell sport competition! 10 minutes of continuous long cycle with 24kg bells - clean and jerk for time. My shoulders are screaming but completing 89 reps in 10 minutes felt incredible. Kettlebell sport is chess match between strength and endurance! ⚡ #KettlebellSport #LongCycle #Competition',
        'image': 'https://images.unsplash.com/photo-1571019613914-85e30c978df2?w=800&h=600&fit=crop',
        'location': 'Iron Sport Gym',
        'timestamp': datetime.now() - timedelta(days=25, hours=5),
        'likes': 367,
        'comments': 56,
        'shares': 23,
        'tags': ['kettlebellsport', 'longcycle', 'competition', 'endurance', 'strength']
    },
    {
        'id': 55,
        'author': 'Sage Summits',
        'username': '@sagesummits',
        'avatar': 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=150&h=150&fit=crop&crop=face',
        'title': 'Multi-Pitch Rock Climbing in Yosemite',
        'text': 'Completed my first multi-pitch climb on El Capitan\'s base routes! 8 pitches of granite perfection with my climbing partner. Multi-pitch climbing is a mental game - route finding, gear management, and trusting your partner completely. Yosemite granite is pure magic! 🧗‍♀️ #MultiPitch #Yosemite #ElCapitan',
        'image': 'https://images.unsplash.com/photo-1522163182402-834f871fd851?w=800&h=600&fit=crop',
        'location': 'Yosemite National Park, California',
        'timestamp': datetime.now() - timedelta(days=26),
        'likes': 734,
        'comments': 112,
        'shares': 58,
        'tags': ['multipitch', 'yosemite', 'elcapitan', 'rockclimbing', 'granite']
    },
    {
        'id': 56,
        'author': 'River Resilience',
        'username': '@riverresilience',
        'avatar': 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&h=150&fit=crop&crop=face',
        'title': 'Contrast Therapy - Heat and Cold',
        'text': 'Alternated between 180°F sauna and 38°F ice bath for 6 rounds today! Contrast therapy supercharges recovery and builds mental resilience. The transition from extreme heat to cold shock activates your nervous system like nothing else. Comfort zones are overrated! 🔥❄️ #ContrastTherapy #Sauna #IceBath',
        'image': 'https://images.unsplash.com/photo-1571019613914-85e30c978df2?w=800&h=600&fit=crop',
        'location': 'Nordic Spa Resort',
        'timestamp': datetime.now() - timedelta(days=26, hours=6),
        'likes': 423,
        'comments': 87,
        'shares': 39,
        'tags': ['contrasttherapy', 'sauna', 'icebath', 'recovery', 'resilience']
    },
    {
        'id': 57,
        'author': 'Nova Nomad',
        'username': '@novanomad',
        'avatar': 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=150&h=150&fit=crop&crop=face',
        'title': 'Van Life in New Zealand\'s South Island',
        'text': 'Month 3 of van life exploring New Zealand\'s South Island! Woke up to this view of Lake Tekapo and couldn\'t believe it\'s real. Living in 60 square feet teaches you what you actually need vs what you think you need. Freedom tastes like morning coffee with mountain views! 🚐 #VanLife #NewZealand #LakeTekapo',
        'image': 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
        'location': 'Lake Tekapo, New Zealand',
        'timestamp': datetime.now() - timedelta(days=27),
        'likes': 892,
        'comments': 156,
        'shares': 78,
        'tags': ['vanlife', 'newzealand', 'laketekapo', 'nomad', 'freedom']
    },
    {
        'id': 58,
        'author': 'Titan Training',
        'username': '@titantraining',
        'avatar': 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&h=150&fit=crop&crop=face',
        'title': 'Olympic Weightlifting - Clean and Jerk PR',
        'text': 'New PR in the clean and jerk - 275lbs! 6 months of technique work with my coach finally paid off. Olympic lifting is pure poetry - explosive power, perfect timing, and flawless technique all coming together in 2 seconds. The barbell doesn\'t lie! 🏋️‍♂️ #OlympicLifting #CleanAndJerk #PR',
        'image': 'https://images.unsplash.com/photo-1571019613914-85e30c978df2?w=800&h=600&fit=crop',
        'location': 'Olympic Training Center',
        'timestamp': datetime.now() - timedelta(days=27, hours=4),
        'likes': 567,
        'comments': 89,
        'shares': 43,
        'tags': ['olympiclifting', 'cleanandjerk', 'pr', 'weightlifting', 'technique']
    },
    {
        'id': 59,
        'author': 'Coral Current',
        'username': '@coralcurrent',
        'avatar': 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face',
        'title': 'Freediving with Manta Rays in Maldives',
        'text': 'Held my breath for 3 minutes while swimming alongside gentle giants! Manta rays are incredibly graceful creatures with wingspans up to 20 feet. Freediving teaches you to be completely present - when you\'re 60 feet underwater on one breath, nothing else matters. Pure meditation! 🌊 #Freediving #MantaRays #Maldives',
        'image': 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&h=600&fit=crop',
        'location': 'Hanifaru Bay, Maldives',
        'timestamp': datetime.now() - timedelta(days=28),
        'likes': 745,
        'comments': 134,
        'shares': 67,
        'tags': ['freediving', 'mantarays', 'maldives', 'underwater', 'meditation']
    },
    {
        'id': 60,
        'author': 'Zen Zenith',
        'username': '@zenzenith',
        'avatar': 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop&crop=face',
        'title': 'Vipassana Meditation - 10 Day Silent Retreat',
        'text': 'Completed my first 10-day Vipassana meditation retreat! No talking, reading, writing, or eye contact for 10 days - just observing the mind. The mental clarity and equanimity gained from this ancient technique is profound. Sometimes the greatest journey is inward! 🧘‍♀️ #Vipassana #Meditation #SilentRetreat',
        'image': 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
        'location': 'Dhamma Meditation Center',
        'timestamp': datetime.now() - timedelta(days=28, hours=8),
        'likes': 456,
        'comments': 98,
        'shares': 54,
        'tags': ['vipassana', 'meditation', 'silentretreat', 'mindfulness', 'equanimity']
    },
    {
        'id': 61,
        'author': 'Storm Skydiver',
        'username': '@stormskydiver',
        'avatar': 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face',
        'title': 'BASE Jumping in the Swiss Alps',
        'text': 'Leaped off a 3,000-foot cliff in Lauterbrunnen Valley today! 45 seconds of pure freefall before deploying my wingsuit. BASE jumping is the ultimate test of preparation, courage, and respect for the mountains. Every jump teaches you something new about fear and focus! 🪂 #BASEJumping #Wingsuit #SwissAlps',
        'image': 'https://images.unsplash.com/photo-1544966503-7cc532d5a35a?w=800&h=600&fit=crop',
        'location': 'Lauterbrunnen, Switzerland',
        'timestamp': datetime.now() - timedelta(days=29),
        'likes': 1023,
        'comments': 198,
        'shares': 89,
        'tags': ['basejumping', 'wingsuit', 'swissalps', 'lauterbrunnen', 'extreme']
    },
    {
        'id': 62,
        'author': 'Luna Lifter',
        'username': '@lunalifter',
        'avatar': 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&h=150&fit=crop&crop=face',
        'title': 'Powerlifting Meet - Triple Bodyweight Deadlift',
        'text': 'Pulled 3x my bodyweight at today\'s powerlifting meet! 405lbs at 135lbs bodyweight felt incredible. 18 months of consistent training, proper programming, and believing in the process. Powerlifting teaches you that strength is earned one rep at a time! 💪 #Powerlifting #Deadlift #TripleBodyweight #Meet',
        'image': 'https://images.unsplash.com/photo-1571019613914-85e30c978df2?w=800&h=600&fit=crop',
        'location': 'Iron Paradise Gym',
        'timestamp': datetime.now() - timedelta(days=29, hours=5),
        'likes': 678,
        'comments': 134,
        'shares': 56,
        'tags': ['powerlifting', 'deadlift', 'triplebodyweight', 'meet', 'strength']
    },
    {
        'id': 63,
        'author': 'Phoenix Pilgrim',
        'username': '@phoenixpilgrim',
        'avatar': 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&h=150&fit=crop&crop=face',
        'title': 'Camino de Santiago - 800km Walking Pilgrimage',
        'text': 'Completed the Camino de Santiago after 35 days of walking! 800 kilometers from France to Spain carrying everything I needed on my back. This ancient pilgrimage route transforms you - physically, mentally, and spiritually. Every blister was worth it! 🚶‍♂️ #CaminoDeSantiago #Pilgrimage #Spain #Walking',
        'image': 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
        'location': 'Santiago de Compostela, Spain',
        'timestamp': datetime.now() - timedelta(days=30),
        'likes': 789,
        'comments': 167,
        'shares': 78,
        'tags': ['camino', 'pilgrimage', 'spain', 'walking', 'spiritual']
    },
    {
        'id': 64,
        'author': 'Blaze Boarder',
        'username': '@blazeboarder',
        'avatar': 'https://images.unsplash.com/photo-1566492031773-4f4e44671d66?w=150&h=150&fit=crop&crop=face',
        'title': 'Snowboarding Japan\'s Legendary Powder',
        'text': 'Riding the legendary powder of Niseko, Hokkaido! 3 feet of fresh snow overnight and I was first on the mountain at dawn. Japanese powder is like floating on clouds - so light and deep you disappear completely. This is what snowboarding dreams are made of! 🏂 #Snowboarding #Japan #Niseko #Powder',
        'image': 'https://images.unsplash.com/photo-1551524164-6cf96ac6d5c5?w=800&h=600&fit=crop',
        'location': 'Niseko, Hokkaido, Japan',
        'timestamp': datetime.now() - timedelta(days=30, hours=7),
        'likes': 834,
        'comments': 145,
        'shares': 67,
        'tags': ['snowboarding', 'japan', 'niseko', 'powder', 'hokkaido']
    },
    {
        'id': 65,
        'author': 'Sage Swimmer',
        'username': '@sageswimmer',
        'avatar': 'https://images.unsplash.com/photo-1525134479668-1bee5c7c6845?w=150&h=150&fit=crop&crop=face',
        'title': 'Ice Swimming in Finnish Lapland',
        'text': 'Jumped into a frozen lake at -20°C in Finnish Lapland! Ice swimming (avantouinti) is a traditional Finnish practice that boosts immunity and mental resilience. The initial shock gives way to incredible euphoria. Cold water therapy at its most extreme! 🧊 #IceSwimming #Finland #Lapland #ColdTherapy',
        'image': 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&h=600&fit=crop',
        'location': 'Rovaniemi, Finland',
        'timestamp': datetime.now() - timedelta(days=31),
        'likes': 567,
        'comments': 98,
        'shares': 45,
        'tags': ['iceswimming', 'finland', 'lapland', 'coldtherapy', 'avantouinti']
    },
    {
        'id': 66,
        'author': 'Atlas Adventurer',
        'username': '@atlasadventurer',
        'avatar': 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
        'title': 'Motorcycle Adventure Through Patagonia',
        'text': 'Day 21 of riding my adventure bike through Patagonia! Crossed from Argentina to Chile via remote mountain passes. Adventure motorcycling combines technical riding skills with pure exploration. When your bike is your lifeline, every mile teaches you self-reliance! 🏍️ #AdventureBike #Patagonia #Motorcycle #Chile',
        'image': 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&h=600&fit=crop',
        'location': 'Torres del Paine, Chile',
        'timestamp': datetime.now() - timedelta(days=31, hours=4),
        'likes': 645,
        'comments': 87,
        'shares': 52,
        'tags': ['adventurebike', 'patagonia', 'motorcycle', 'chile', 'exploration']
    },
    {
        'id': 67,
        'author': 'Harmony Health',
        'username': '@harmonyhealth',
        'avatar': 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&h=150&fit=crop&crop=face',
        'title': 'Functional Medicine Approach to Wellness',
        'text': 'Completed comprehensive functional medicine testing to optimize my health! Genetic testing, microbiome analysis, and nutrient panels revealed so much about my body\'s unique needs. Functional medicine looks at root causes, not just symptoms. Knowledge is power! 🧬 #FunctionalMedicine #Wellness #Health #Optimization',
        'image': 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=800&h=600&fit=crop',
        'location': 'Integrative Health Center',
        'timestamp': datetime.now() - timedelta(days=32),
        'likes': 423,
        'comments': 134,
        'shares': 67,
        'tags': ['functionalmedicine', 'wellness', 'health', 'optimization', 'testing']
    },
    {
        'id': 68,
        'author': 'River Runner',
        'username': '@riverrunner',
        'avatar': 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
        'title': 'Grand Canyon Rim-to-Rim Hike',
        'text': 'Completed the Grand Canyon rim-to-rim hike in one day! 24 miles from South Rim to North Rim with 6,000 feet of elevation change. Starting at 4 AM with headlamps, the sunrise over the canyon was magical. This hike humbles you with the raw power of geological time! 🏔️ #GrandCanyon #RimToRim #Hiking #Arizona',
        'image': 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
        'location': 'Grand Canyon National Park, Arizona',
        'timestamp': datetime.now() - timedelta(days=32, hours=6),
        'likes': 789,
        'comments': 156,
        'shares': 89,
        'tags': ['grandcanyon', 'rimtorim', 'hiking', 'arizona', 'endurance']
    },
    {
        'id': 69,
        'author': 'Nova Ninja',
        'username': '@novaninja',
        'avatar': 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face',
        'title': 'Ninja Warrior Training - Obstacle Mastery',
        'text': 'Finally conquered the warped wall after months of training! Ninja warrior training combines strength, agility, and problem-solving in the most creative ways. Every obstacle teaches you something new about body mechanics and mental persistence. Failure is just feedback! 🥷 #NinjaWarrior #Obstacles #Training #WarpedWall',
        'image': 'https://images.unsplash.com/photo-1571019613914-85e30c978df2?w=800&h=600&fit=crop',
        'location': 'Ultimate Athletics Gym',
        'timestamp': datetime.now() - timedelta(days=33),
        'likes': 567,
        'comments': 89,
        'shares': 43,
        'tags': ['ninjawarrior', 'obstacles', 'training', 'warpedwall', 'agility']
    },
    {
        'id': 70,
        'author': 'Zen Zone',
        'username': '@zenzone',
        'avatar': 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop&crop=face',
        'title': 'Sound Bath Meditation - Healing Frequencies',
        'text': 'Experienced my first sound bath meditation with crystal bowls, gongs, and chimes! The healing frequencies created such deep relaxation that I felt like I was floating. Sound therapy has been used for thousands of years to restore balance and harmony. Pure sonic bliss! 🎵 #SoundBath #Meditation #HealingFrequencies #Wellness',
        'image': 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&h=600&fit=crop',
        'location': 'Sacred Sound Studio',
        'timestamp': datetime.now() - timedelta(days=33, hours=8),
        'likes': 398,
        'comments': 76,
        'shares': 54,
        'tags': ['soundbath', 'meditation', 'healingfrequencies', 'wellness', 'relaxation']
    },
    {
        'id': 71,
        'author': 'Titan Trekker',
        'username': '@titantrekker',
        'avatar': 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&h=150&fit=crop&crop=face',
        'title': 'Kilimanjaro Summit - Uhuru Peak',
        'text': 'Made it to the roof of Africa! 19,341 feet above sea level after 7 days of trekking. The final summit push started at midnight in -15°C weather. Watching sunrise from Uhuru Peak was pure magic. Kilimanjaro teaches you that every step forward is progress! ⛰️ #Kilimanjaro #Tanzania #UhuruPeak #Summit',
        'image': 'https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=800&h=600&fit=crop',
        'location': 'Mount Kilimanjaro, Tanzania',
        'timestamp': datetime.now() - timedelta(days=34),
        'likes': 923,
        'comments': 187,
        'shares': 94,
        'tags': ['kilimanjaro', 'tanzania', 'uhurupeak', 'summit', 'africa']
    },
    {
        'id': 72,
        'author': 'Flex Flow',
        'username': '@flexflow',
        'avatar': 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face',
        'title': 'Contortion Training - Mind-Body Connection',
        'text': 'Started contortion training to explore the limits of human flexibility! Today I achieved my first chest stand after months of dedicated stretching. Contortion is like meditation in motion - it requires complete presence and trust in your body\'s capabilities! 🤸‍♀️ #Contortion #Flexibility #ChestStand #Movement',
        'image': 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&h=600&fit=crop',
        'location': 'Cirque Studio',
        'timestamp': datetime.now() - timedelta(days=34, hours=5),
        'likes': 456,
        'comments': 89,
        'shares': 37,
        'tags': ['contortion', 'flexibility', 'cheststand', 'movement', 'circus']
    },
    {
        'id': 73,
        'author': 'Storm Sailor',
        'username': '@stormsailor',
        'avatar': 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face',
        'title': 'Atlantic Ocean Crossing - Solo Sailing',
        'text': 'Day 42 of my solo Atlantic crossing! Just passed the halfway point between Portugal and Caribbean. Living alone on a 35-foot sailboat for weeks teaches you everything about self-reliance and patience. The ocean is my teacher and the wind is my engine! ⛵ #SoloSailing #Atlantic #OceanCrossing #Sailing',
        'image': 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
        'location': 'Mid-Atlantic Ocean',
        'timestamp': datetime.now() - timedelta(days=35),
        'likes': 734,
        'comments': 134,
        'shares': 67,
        'tags': ['solosailing', 'atlantic', 'oceancrossing', 'sailing', 'adventure']
    },
    {
        'id': 74,
        'author': 'Apex Athlete',
        'username': '@apexathlete',
        'avatar': 'https://images.unsplash.com/photo-1566492031773-4f4e44671d66?w=150&h=150&fit=crop&crop=face',
        'title': 'Decathlon Training - 10 Events in 2 Days',
        'text': 'Completed my first decathlon competition! 10 track and field events over 2 days testing every athletic ability. From 100m sprints to pole vault to 1500m endurance - decathlon is the ultimate test of well-rounded athleticism. Jack of all trades, master of... persistence! 🏃‍♂️ #Decathlon #TrackAndField #TenEvents #Athletics',
        'image': 'https://images.unsplash.com/photo-1571019613914-85e30c978df2?w=800&h=600&fit=crop',
        'location': 'University Stadium',
        'timestamp': datetime.now() - timedelta(days=35, hours=6),
        'likes': 567,
        'comments': 98,
        'shares': 45,
        'tags': ['decathlon', 'trackandfield', 'tenevents', 'athletics', 'competition']
    },
    {
        'id': 75,
        'author': 'Mystic Mountain',
        'username': '@mysticmountain',
        'avatar': 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=150&h=150&fit=crop&crop=face',
        'title': 'Ayahuasca Ceremony in the Amazon',
        'text': 'Participated in a traditional ayahuasca ceremony with indigenous shamans in the Peruvian Amazon. This sacred plant medicine journey was profoundly transformative - confronting fears, releasing old patterns, and connecting with something greater than myself. Healing comes in many forms! 🌿 #Ayahuasca #Amazon #PlantMedicine #Healing',
        'image': 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
        'location': 'Iquitos, Peruvian Amazon',
        'timestamp': datetime.now() - timedelta(days=36),
        'likes': 645,
        'comments': 156,
        'shares': 78,
        'tags': ['ayahuasca', 'amazon', 'plantmedicine', 'healing', 'shamanic']
    },
    {
        'id': 76,
        'author': 'Thunder Thrower',
        'username': '@thunderthrower',
        'avatar': 'https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=150&h=150&fit=crop&crop=face',
        'title': 'Highland Games - Caber Toss Champion',
        'text': 'Won the caber toss at the Highland Games! Throwing a 19-foot, 175-pound log end over end requires technique, timing, and raw power. Highland Games connect you to ancient Scottish traditions where strength was celebrated. Felt like a warrior today! 🏴󠁧󠁢󠁳󠁣󠁴󠁿 #HighlandGames #CaberToss #Scotland #Strength',
        'image': 'https://images.unsplash.com/photo-1571019613914-85e30c978df2?w=800&h=600&fit=crop',
        'location': 'Scottish Highland Festival',
        'timestamp': datetime.now() - timedelta(days=36, hours=4),
        'likes': 489,
        'comments': 76,
        'shares': 34,
        'tags': ['highlandgames', 'cabertoss', 'scotland', 'strength', 'tradition']
    },
    {
        'id': 77,
        'author': 'Echo Explorer',
        'username': '@echoexplorer',
        'avatar': 'https://images.unsplash.com/photo-1463453091185-61582044d556?w=150&h=150&fit=crop&crop=face',
        'title': 'Dog Sledding Across Greenland Ice Sheet',
        'text': 'Week 2 of crossing Greenland\'s ice sheet by dog sled! These incredible Greenlandic huskies are built for this terrain. Temperatures drop to -40°C but the aurora borealis at night makes it magical. Dog sledding teaches you to work as a team with nature! 🐕 #DogSledding #Greenland #IceSheet #Aurora #Huskies',
        'image': 'https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=800&h=600&fit=crop',
        'location': 'Greenland Ice Sheet',
        'timestamp': datetime.now() - timedelta(days=37),
        'likes': 823,
        'comments': 145,
        'shares': 89,
        'tags': ['dogsledding', 'greenland', 'icesheet', 'aurora', 'huskies']
    },
    {
        'id': 78,
        'author': 'Primal Power',
        'username': '@primalpower',
        'avatar': 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&h=150&fit=crop&crop=face',
        'title': 'MovNat Training - Natural Movement',
        'text': 'Embracing MovNat (Natural Movement) training in the wilderness! Crawling, climbing, jumping, and carrying objects the way our ancestors moved. Modern gyms are great, but moving naturally in nature awakens something primal and powerful within us! 🌲 #MovNat #NaturalMovement #Primal #Wilderness #Functional',
        'image': 'https://images.unsplash.com/photo-1571019613914-85e30c978df2?w=800&h=600&fit=crop',
        'location': 'Redwood National Park',
        'timestamp': datetime.now() - timedelta(days=37, hours=7),
        'likes': 398,
        'comments': 67,
        'shares': 43,
        'tags': ['movnat', 'naturalmovement', 'primal', 'wilderness', 'functional']
    },
    {
        'id': 79,
        'author': 'Coral Crusader',
        'username': '@coralcrusader',
        'avatar': 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=150&h=150&fit=crop&crop=face',
        'title': 'Underwater Photography in Raja Ampat',
        'text': 'Diving in Raja Ampat, Indonesia - the most biodiverse marine environment on Earth! Swimming through schools of barracuda while photographing manta rays and reef sharks. Underwater photography teaches patience and respect for marine life. Every dive is a privilege! 📸 #UnderwaterPhotography #RajaAmpat #Indonesia #MarineLife #Diving',
        'image': 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&h=600&fit=crop',
        'location': 'Raja Ampat, Indonesia',
        'timestamp': datetime.now() - timedelta(days=38),
        'likes': 712,
        'comments': 123,
        'shares': 67,
        'tags': ['underwaterphotography', 'rajaampat', 'indonesia', 'marinelife', 'diving']
    },
    {
        'id': 80,
        'author': 'Serenity Soul',
        'username': '@serenitysoul',
        'avatar': 'https://images.unsplash.com/photo-1525134479668-1bee5c7c6845?w=150&h=150&fit=crop&crop=face',
        'title': 'Sensory Deprivation Float Tank - Deep Meditation',
        'text': 'Spent 90 minutes in a sensory deprivation float tank filled with Epsom salt water! Complete darkness, silence, and weightlessness create the perfect environment for deep meditation. Without external stimuli, your mind travels to incredible places. Inner space exploration! 🌌 #FloatTank #SensoryDeprivation #Meditation #InnerSpace #Consciousness',
        'image': 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&h=600&fit=crop',
        'location': 'Float Wellness Center',
        'timestamp': datetime.now() - timedelta(days=38, hours=5),
        'likes': 445,
        'comments': 89,
        'shares': 56,
        'tags': ['floattank', 'sensorydeprivation', 'meditation', 'innerspace', 'consciousness']
    },
    {
        'id': 81,
        'author': 'Blaze Boarder',
        'username': '@blazeboarder',
        'avatar': 'https://images.unsplash.com/photo-1552374196-c4e7ffc6e126?w=150&h=150&fit=crop&crop=face',
        'title': 'Kitesurfing in Cape Town - 40 Knot Winds',
        'text': 'Epic kitesurfing session in Table Bay with 40-knot winds! Flying 30 feet above the water with Table Mountain as backdrop was surreal. Kitesurfing teaches you to harness nature\'s power while respecting its unpredictability. Wind therapy at its finest! 🪁 #Kitesurfing #CapeTown #TableMountain #WindPower #SouthAfrica',
        'image': 'https://images.unsplash.com/photo-1544966503-7cc532d5a35a?w=800&h=600&fit=crop',
        'location': 'Table Bay, Cape Town, South Africa',
        'timestamp': datetime.now() - timedelta(days=39),
        'likes': 678,
        'comments': 123,
        'shares': 56,
        'tags': ['kitesurfing', 'capetown', 'tablemountain', 'windpower', 'southafrica']
    },
    {
        'id': 82,
        'author': 'Jade Jujitsu',
        'username': '@jadejujitsu',
        'avatar': 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&h=150&fit=crop&crop=face',
        'title': 'Brazilian Jiu-Jitsu Blue Belt Promotion',
        'text': 'Finally earned my blue belt in Brazilian Jiu-Jitsu after 18 months of training! BJJ is physical chess - every position has counters and escapes. Getting submitted thousands of times taught me that ego has no place on the mats. Oss! 🥋 #BJJ #BrazilianJiuJitsu #BlueBelt #MartialArts #Oss',
        'image': 'https://images.unsplash.com/photo-1571019613914-85e30c978df2?w=800&h=600&fit=crop',
        'location': 'Gracie Academy',
        'timestamp': datetime.now() - timedelta(days=39, hours=4),
        'likes': 456,
        'comments': 89,
        'shares': 34,
        'tags': ['bjj', 'brazilianjujitsu', 'bluebelt', 'martialarts', 'oss']
    },
    {
        'id': 83,
        'author': 'Frost Fighter',
        'username': '@frostfighter',
        'avatar': 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face',
        'title': 'Arctic Expedition - North Pole Trek',
        'text': 'Day 15 of skiing to the North Pole! Pulling a 200lb sled across shifting sea ice in -40°C temperatures. Polar bears, pressure ridges, and complete whiteouts test every survival skill. The Arctic teaches you humility like nowhere else on Earth! 🧊 #ArcticExpedition #NorthPole #PolarExploration #Survival #Arctic',
        'image': 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&h=600&fit=crop',
        'location': 'Arctic Ocean, North Pole',
        'timestamp': datetime.now() - timedelta(days=40),
        'likes': 834,
        'comments': 167,
        'shares': 89,
        'tags': ['arcticexpedition', 'northpole', 'polarexploration', 'survival', 'arctic']
    },
    {
        'id': 84,
        'author': 'Luna Lifter',
        'username': '@lunalifter',
        'avatar': 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face',
        'title': 'Gymnastics Rings Training - Iron Cross Hold',
        'text': 'Achieved my first 5-second iron cross on gymnastics rings! Months of strength building and technique work finally paid off. Ring training builds incredible functional strength and body control. Every hold teaches you something new about leverage and balance! 💪 #GymnasticsRings #IronCross #Calisthenics #Strength #Gymnastics',
        'image': 'https://images.unsplash.com/photo-1571019613914-85e30c978df2?w=800&h=600&fit=crop',
        'location': 'Elite Gymnastics Center',
        'timestamp': datetime.now() - timedelta(days=40, hours=6),
        'likes': 567,
        'comments': 98,
        'shares': 45,
        'tags': ['gymnasticsrings', 'ironcross', 'calisthenics', 'strength', 'gymnastics']
    },
    {
        'id': 85,
        'author': 'Sage Spelunker',
        'username': '@sagespelunker',
        'avatar': 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&h=150&fit=crop&crop=face',
        'title': 'Cave Exploration in Mammoth Cave System',
        'text': 'Spent 12 hours exploring uncharted passages in Mammoth Cave! Crawling through tight squeezes and rappelling into vast chambers that haven\'t seen sunlight in millions of years. Caving teaches patience, teamwork, and respect for Earth\'s hidden wonders! 🕳️ #Caving #MammothCave #Spelunking #Underground #Exploration',
        'image': 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
        'location': 'Mammoth Cave National Park, Kentucky',
        'timestamp': datetime.now() - timedelta(days=41),
        'likes': 645,
        'comments': 112,
        'shares': 67,
        'tags': ['caving', 'mammothcave', 'spelunking', 'underground', 'exploration']
    },
    {
        'id': 86,
        'author': 'Phoenix Paddler',
        'username': '@phoenixpaddler',
        'avatar': 'https://images.unsplash.com/photo-1463453091185-61582044d556?w=150&h=150&fit=crop&crop=face',
        'title': 'Stand-Up Paddleboard Yoga in Bali',
        'text': 'Morning SUP yoga session on the calm waters of Sanur Beach! Balancing in warrior pose while floating on water adds a whole new dimension to practice. SUP yoga challenges your core and teaches you to find stability in constant motion! 🧘‍♀️ #SUPYoga #Bali #StandUpPaddleboard #Yoga #Balance',
        'image': 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&h=600&fit=crop',
        'location': 'Sanur Beach, Bali',
        'timestamp': datetime.now() - timedelta(days=41, hours=5),
        'likes': 523,
        'comments': 87,
        'shares': 43,
        'tags': ['supyoga', 'bali', 'standuppaddleboard', 'yoga', 'balance']
    },
    {
        'id': 87,
        'author': 'Atlas Alpine',
        'username': '@atlasalpine',
        'avatar': 'https://images.unsplash.com/photo-1566492031773-4f4e44671d66?w=150&h=150&fit=crop&crop=face',
        'title': 'Alpine Climbing - Mont Blanc Summit',
        'text': 'Reached the summit of Mont Blanc via the classic Goûter route! 15,777 feet of technical alpine climbing with crampons, ice axes, and ropes. Alpine climbing combines mountaineering skills with weather reading and risk management. Europe\'s highest peak conquered! ⛰️ #AlpineClimbing #MontBlanc #Mountaineering #Alps #Summit',
        'image': 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
        'location': 'Mont Blanc, French Alps',
        'timestamp': datetime.now() - timedelta(days=42),
        'likes': 789,
        'comments': 145,
        'shares': 78,
        'tags': ['alpineclimbing', 'montblanc', 'mountaineering', 'alps', 'summit']
    },
    {
        'id': 88,
        'author': 'River Renewal',
        'username': '@riverrenewal',
        'avatar': 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&h=150&fit=crop&crop=face',
        'title': 'Holotropic Breathwork - Consciousness Journey',
        'text': 'Experienced holotropic breathwork for the first time! 3 hours of accelerated breathing induced altered states of consciousness without any substances. The healing potential of conscious breathing is incredible - accessing memories, releasing trauma, and expanding awareness! 🌀 #HolotropicBreathwork #Consciousness #Healing #Breathwork #Wellness',
        'image': 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&h=600&fit=crop',
        'location': 'Holistic Healing Center',
        'timestamp': datetime.now() - timedelta(days=42, hours=7),
        'likes': 398,
        'comments': 134,
        'shares': 89,
        'tags': ['holotropicbreathwork', 'consciousness', 'healing', 'breathwork', 'wellness']
    },
    {
        'id': 89,
        'author': 'Storm Skater',
        'username': '@stormskater',
        'avatar': 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
        'title': 'Skateboarding the Empty Swimming Pools',
        'text': 'Found some abandoned pools and spent the day carving concrete bowls! Skateboarding teaches you to see urban decay as opportunity for creativity. Every slam teaches resilience and every make builds confidence. Pool skating is pure flow state! 🛹 #Skateboarding #PoolSkating #Bowls #UrbanExploration #FlowState',
        'image': 'https://images.unsplash.com/photo-1578764689717-9c4e43e2b65a?w=800&h=600&fit=crop',
        'location': 'Abandoned Pool Complex',
        'timestamp': datetime.now() - timedelta(days=43),
        'likes': 456,
        'comments': 76,
        'shares': 34,
        'tags': ['skateboarding', 'poolskating', 'bowls', 'urbanexploration', 'flowstate']
    },
    {
        'id': 90,
        'author': 'Nova Navigator',
        'username': '@novanavigator',
        'avatar': 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face',
        'title': 'Desert Ultramarathon - 100 Miles in Sahara',
        'text': 'Completed the 100-mile Sahara Desert ultramarathon! 6 stages across sand dunes in 50°C heat carrying all my gear. Desert running strips away everything non-essential - just you, the sand, and pure determination. Mind over matter! 🏃‍♀️ #DesertUltramarathon #Sahara #100Miles #Ultrarunning #Endurance',
        'image': 'https://images.unsplash.com/photo-1539650116574-75c0c6d0327a?w=800&h=600&fit=crop',
        'location': 'Sahara Desert, Morocco',
        'timestamp': datetime.now() - timedelta(days=43, hours=4),
        'likes': 712,
        'comments': 156,
        'shares': 89,
        'tags': ['desertultramarathon', 'sahara', '100miles', 'ultrarunning', 'endurance']
    },
    {
        'id': 91,
        'author': 'Echo Elevation',
        'username': '@echoelevation',
        'avatar': 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
        'title': 'Via Ferrata Climbing in the Dolomites',
        'text': 'Conquered the Via Ferrata routes in Italy\'s Dolomites! These iron paths let you experience extreme exposure with safety cables and ladders. Via ferrata bridges the gap between hiking and technical climbing. The views from 8,000 feet are absolutely breathtaking! 🏔️ #ViaFerrata #Dolomites #Italy #IronPath #Climbing',
        'image': 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
        'location': 'Dolomites, Northern Italy',
        'timestamp': datetime.now() - timedelta(days=44),
        'likes': 623,
        'comments': 98,
        'shares': 52,
        'tags': ['viaferrata', 'dolomites', 'italy', 'ironpath', 'climbing']
    },
    {
        'id': 92,
        'author': 'Bliss Balance',
        'username': '@blissbalance',
        'avatar': 'https://images.unsplash.com/photo-1525134479668-1bee5c7c6845?w=150&h=150&fit=crop&crop=face',
        'title': 'Acro Yoga Partnership - Flying High',
        'text': 'Spent the afternoon practicing acro yoga with my partner! Base and flyer working together to create beautiful flowing sequences in the air. Acro yoga builds trust, communication, and core strength while being incredibly fun. Relationships are the ultimate practice! 🤸‍♀️ #AcroYoga #Partnership #Trust #Balance #Flying',
        'image': 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&h=600&fit=crop',
        'location': 'Beachside Park',
        'timestamp': datetime.now() - timedelta(days=44, hours=6),
        'likes': 445,
        'comments': 87,
        'shares': 56,
        'tags': ['acroyoga', 'partnership', 'trust', 'balance', 'flying']
    },
    {
        'id': 93,
        'author': 'Titan Tracker',
        'username': '@titantracker',
        'avatar': 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&h=150&fit=crop&crop=face',
        'title': 'Bushcraft Survival - 7 Days Alone in Wilderness',
        'text': 'Survived 7 days in the wilderness with only a knife! Built shelter, made fire, purified water, and foraged food using primitive skills. Bushcraft connects you to ancestral knowledge and teaches self-reliance. Nature provides everything if you know how to look! 🌲 #Bushcraft #Survival #Wilderness #Primitive #SelfReliance',
        'image': 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
        'location': 'Olympic National Forest',
        'timestamp': datetime.now() - timedelta(days=45),
        'likes': 567,
        'comments': 123,
        'shares': 67,
        'tags': ['bushcraft', 'survival', 'wilderness', 'primitive', 'selfreliance']
    },
    {
        'id': 94,
        'author': 'Coral Consciousness',
        'username': '@coralconsciousness',
        'avatar': 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=150&h=150&fit=crop&crop=face',
        'title': 'Dolphin Swimming in Azores',
        'text': 'Swam with wild dolphins in the crystal waters of the Azores! These intelligent beings approached us with such curiosity and playfulness. Swimming with dolphins in their natural habitat is a profound reminder of our connection to all life on Earth! 🐬 #DolphinSwimming #Azores #MarineLife #Portugal #Ocean',
        'image': 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&h=600&fit=crop',
        'location': 'Azores, Portugal',
        'timestamp': datetime.now() - timedelta(days=45, hours=5),
        'likes': 834,
        'comments': 167,
        'shares': 94,
        'tags': ['dolphinswimming', 'azores', 'marinelife', 'portugal', 'ocean']
    },
    {
        'id': 95,
        'author': 'Phoenix Power',
        'username': '@phoenixpower',
        'avatar': 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=150&h=150&fit=crop&crop=face',
        'title': 'Pole Dancing Fitness - Strength and Grace',
        'text': 'Discovered pole dancing fitness and I\'m amazed by the athleticism required! The combination of strength, flexibility, and artistry is incredible. Pole dancing challenges every muscle while building confidence and self-expression. Art meets athletics! 💃 #PoleDancing #Fitness #Strength #Grace #Art',
        'image': 'https://images.unsplash.com/photo-1571019613914-85e30c978df2?w=800&h=600&fit=crop',
        'location': 'Vertical Dance Studio',
        'timestamp': datetime.now() - timedelta(days=46),
        'likes': 478,
        'comments': 89,
        'shares': 45,
        'tags': ['poledancing', 'fitness', 'strength', 'grace', 'art']
    },
    {
        'id': 96,
        'author': 'Storm Swimmer',
        'username': '@stormswimmer',
        'avatar': 'https://images.unsplash.com/photo-1552374196-c4e7ffc6e126?w=150&h=150&fit=crop&crop=face',
        'title': 'English Channel Swim - 21 Miles of Determination',
        'text': 'SWAM THE ENGLISH CHANNEL! 21 miles from England to France in 14 hours and 23 minutes. Jellyfish stings, hypothermia, and massive swells tested every ounce of mental strength. Channel swimming is 90% mental - your body can do far more than your mind thinks! 🏊‍♂️ #EnglishChannel #Marathon Swimming #Dover #France #Endurance',
        'image': 'https://images.unsplash.com/photo-1530549387789-4c1017266635?w=800&h=600&fit=crop',
        'location': 'English Channel',
        'timestamp': datetime.now() - timedelta(days=46, hours=7),
        'likes': 923,
        'comments': 189,
        'shares': 123,
        'tags': ['englishchannel', 'marathonswimming', 'dover', 'france', 'endurance']
    },
    {
        'id': 97,
        'author': 'Jade Journey',
        'username': '@jadejourney',
        'avatar': 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop&crop=face',
        'title': 'Ecstatic Dance - Movement Meditation',
        'text': 'Spent 3 hours in ecstatic dance - free-form movement without choreography or judgment! Dancing to live drums and world music creates such freedom of expression. Ecstatic dance is moving meditation where your body becomes the prayer! 💃 #EcstaticDance #Movement #Meditation #Expression #Freedom',
        'image': 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&h=600&fit=crop',
        'location': 'Sacred Movement Studio',
        'timestamp': datetime.now() - timedelta(days=47),
        'likes': 356,
        'comments': 76,
        'shares': 43,
        'tags': ['ecstaticdance', 'movement', 'meditation', 'expression', 'freedom']
    },
    {
        'id': 98,
        'author': 'Apex Archer',
        'username': '@apexarcher',
        'avatar': 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face',
        'title': 'Traditional Archery in Bhutan Monasteries',
        'text': 'Learning traditional archery from Bhutanese monks in the Himalayas! Using bamboo bows and wooden arrows while chanting mantras creates such mindful focus. Archery here is meditation in motion - breath, aim, release, and let go! 🏹 #TraditionalArchery #Bhutan #Monastery #Meditation #Mindfulness',
        'image': 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
        'location': 'Tiger\'s Nest Monastery, Bhutan',
        'timestamp': datetime.now() - timedelta(days=47, hours=4),
        'likes': 645,
        'comments': 123,
        'shares': 67,
        'tags': ['traditionalarchery', 'bhutan', 'monastery', 'meditation', 'mindfulness']
    },
    {
        'id': 99,
        'author': 'River Rapids',
        'username': '@riverrapids',
        'avatar': 'https://images.unsplash.com/photo-1566492031773-4f4e44671d66?w=150&h=150&fit=crop&crop=face',
        'title': 'Slackline Walking - Finding Balance',
        'text': 'Spent the day slacklining between ancient redwood trees! Walking a 1-inch webbing 50 feet above the ground requires complete presence and trust. Slacklining teaches you that balance isn\'t static - it\'s constant micro-adjustments and flow! 🌲 #Slackline #Balance #Redwoods #Focus #Flow',
        'image': 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
        'location': 'Muir Woods, California',
        'timestamp': datetime.now() - timedelta(days=48),
        'likes': 478,
        'comments': 89,
        'shares': 34,
        'tags': ['slackline', 'balance', 'redwoods', 'focus', 'flow']
    },
    {
        'id': 100,
        'author': 'Zen Zenith',
        'username': '@zenzenith',
        'avatar': 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&h=150&fit=crop&crop=face',
        'title': 'Digital Detox - 30 Days Offline',
        'text': 'Completed a 30-day digital detox - no phone, internet, or screens! Spent the time reading books, writing in journals, and having real conversations. Digital detox reminded me that life\'s most meaningful moments happen when we\'re fully present. Connection over connectivity! 📚 #DigitalDetox #Mindfulness #Present #Books #Connection',
        'image': 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&h=600&fit=crop',
        'location': 'Mountain Cabin Retreat',
        'timestamp': datetime.now() - timedelta(days=48, hours=6),
        'likes': 567,
        'comments': 134,
        'shares': 89,
        'tags': ['digitaldetox', 'mindfulness', 'present', 'books', 'connection']
    }
]
