# Generated by Django 4.2.7 on 2025-08-25 12:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('type', models.CharField(default='advertisement', max_length=50)),
                ('brand', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('image', models.URLField(max_length=500)),
                ('cta_text', models.CharField(help_text='Button text like "Shop Now"', max_length=100)),
                ('cta_link', models.URLField(help_text='Link when CTA button is clicked', max_length=500)),
                ('category', models.CharField(help_text='e.g., Outdoor Gear, Health & Wellness', max_length=100)),
                ('promoted', models.BooleanField(default=True)),
                ('target_audience', models.JSONField(blank=True, default=list, help_text='List of interests to target')),
                ('budget_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('impressions', models.PositiveIntegerField(default=0, help_text='Number of times ad was shown')),
                ('clicks', models.PositiveIntegerField(default=0, help_text='Number of times ad was clicked')),
                ('is_active', models.BooleanField(default=True, help_text='Whether ad is currently active')),
                ('start_date', models.DateTimeField(blank=True, help_text='When ad campaign starts', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='When ad campaign ends', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
                'db_table': 'feed_advertisements',
                'ordering': ['-created_at'],
            },
        ),
    ]
