# Generated by Django 4.2.7 on 2025-08-26 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0002_advertisement'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(help_text='Interest name from post tags', max_length=100)),
                ('score', models.FloatField(default=1.0, help_text='Interest strength score')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Interest',
                'verbose_name_plural': 'User Interests',
                'db_table': 'user_interests',
                'ordering': ['-score', 'interest'],
                'unique_together': {('user', 'interest')},
            },
        ),
    ]
