# Generated by Django 4.2.7 on 2025-08-26 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0003_userinterest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impression_time', models.DateTimeField(auto_now_add=True)),
                ('view_duration', models.FloatField(default=0.0, help_text='Duration in seconds')),
                ('scroll_depth', models.FloatField(default=0.0, help_text='Percentage of post visible (0.0-1.0)')),
                ('interaction_type', models.CharField(default='view', help_text='view, click, like, etc.', max_length=50)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post Impression',
                'verbose_name_plural': 'Post Impressions',
                'db_table': 'post_impressions',
                'ordering': ['-impression_time'],
                'unique_together': {('user', 'post')},
            },
        ),
    ]
