# Generated by Django 4.2.7 on 2025-08-27 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0004_postimpression'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', to='feed.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post Like',
                'verbose_name_plural': 'Post Likes',
                'db_table': 'post_likes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='post_likes_user_id_7d46ab_idx'), models.Index(fields=['post'], name='post_likes_post_id_c6421f_idx'), models.Index(fields=['created_at'], name='post_likes_created_c52989_idx')],
                'unique_together': {('user', 'post')},
            },
        ),
    ]
