# Generated by Django 4.2.7 on 2025-08-28 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0005_postlike'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_duration', models.FloatField(default=0.0, help_text='How long user viewed ad in seconds')),
                ('viewport_percentage', models.FloatField(default=0.0, help_text='Percentage of ad visible (0.0-1.0)')),
                ('session_key', models.CharField(blank=True, help_text='Session key for anonymous users', max_length=40, null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='User IP address', null=True)),
                ('impression_start', models.DateTimeField(auto_now_add=True)),
                ('impression_end', models.DateTimeField(blank=True, null=True)),
                ('is_valid_impression', models.BooleanField(default=True, help_text='Whether this counts as a valid impression (>= 1 second view)')),
                ('counted_in_analytics', models.BooleanField(default=False, help_text='Whether this impression has been counted in ad analytics')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions_tracked', to='feed.advertisement')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_impressions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ad Impression',
                'verbose_name_plural': 'Ad Impressions',
                'db_table': 'ad_impressions',
                'ordering': ['-impression_start'],
                'indexes': [models.Index(fields=['user', 'advertisement'], name='ad_impressi_user_id_8628fb_idx'), models.Index(fields=['session_key', 'advertisement'], name='ad_impressi_session_f67b1e_idx'), models.Index(fields=['impression_start'], name='ad_impressi_impress_a81b10_idx'), models.Index(fields=['is_valid_impression'], name='ad_impressi_is_vali_518691_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='adimpression',
            constraint=models.UniqueConstraint(condition=models.Q(('impression_start__isnull', False)), fields=('user', 'advertisement', 'impression_start'), name='unique_user_ad_impression_per_minute'),
        ),
    ]
