# Generated by Django 4.2.7 on 2025-08-28 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_adimpression_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='adimpression',
            name='unique_user_ad_impression_per_minute',
        ),
    ]
