# Generated by Django 4.2.7 on 2025-09-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_remove_adimpression_unique_user_ad_impression_per_minute'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='postlike',
            new_name='user_likes_idx',
            old_name='post_likes_user_id_7d46ab_idx',
        ),
        migrations.RenameIndex(
            model_name='postlike',
            new_name='post_likes_idx',
            old_name='post_likes_post_id_c6421f_idx',
        ),
        migrations.RenameIndex(
            model_name='postlike',
            new_name='like_created_idx',
            old_name='post_likes_created_c52989_idx',
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_at'], name='feed_posts_created_fab294_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', '-created_at'], name='feed_posts_author__0df30a_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['likes'], name='post_likes_count_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', 'likes'], name='author_likes_idx'),
        ),
        migrations.AddIndex(
            model_name='postlike',
            index=models.Index(fields=['user', 'post'], name='user_post_like_idx'),
        ),
    ]
