# Generated by Django 4.2.7 on 2025-09-04 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_rename_post_likes_user_id_7d46ab_idx_user_likes_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='feed_posts_created_fab294_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='feed_posts_author__0df30a_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='post_likes_count_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='author_likes_idx',
        ),
        migrations.AlterModelTable(
            name='post',
            table=None,
        ),
    ]
