# Generated by Django 4.2.7 on 2025-09-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_at'], name='feed_posts_created_fab294_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', '-created_at'], name='feed_posts_author__0df30a_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['likes'], name='post_likes_count_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', 'likes'], name='author_likes_idx'),
        ),
        migrations.AlterModelTable(
            name='post',
            table='feed_posts',
        ),
    ]
